import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {loadVerifiedOperatorFhirClient} from '../operator-identity.ts';
const root=resolve(new URL('../..',import.meta.url).pathname),runtime=join(root,'.odos/r10-a3-2-served');
const read=name=>JSON.parse(readFileSync(join(runtime,name),'utf8'));
const manifest=read('manifest.json'),credentials=read('credentials.json'),fixture=read('fixture.json');
assert.equal(manifest.project,'odos-r10-a3-2-served');
const evidence=join(root,'docs/evidence/r10-a3-2/served-route/screens');mkdirSync(evidence,{recursive:true});
const operator=await loadVerifiedOperatorFhirClient({baseUrl:`http://127.0.0.1:${manifest.ports.medplum}`,projectId:credentials.projectId,postgresUrl:`postgresql://medplum:medplum@127.0.0.1:${manifest.ports.postgres}/medplum`,credentialPath:join(runtime,'operator.env'),statePath:join(runtime,'operator-state.json')});
const template=await operator.fhir.read('Encounter',fixture.current.slice(10));
const {id,meta,identifier,diagnosis,...body}=template;
const encounter=await operator.fhir.create({...body,status:'in-progress',period:{start:new Date(Date.UTC(2026,8,20)+Date.now()%86400000).toISOString()}});
const encounterReference=`Encounter/${encounter.id}`;
const result={build:read('identity.json'),encounterReference,initialVersion:encounter.meta.versionId,steps:[],screenshots:[]};
const require=createRequire(join(root,'ui/package.json'));const {chromium}=require('playwright-core');
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const page=await browser.newPage({viewport:{width:1600,height:1100}});page.setDefaultTimeout(20000);
const base=`http://127.0.0.1:${manifest.ports.frontdoor}`;
async function api(path,method='GET',body){return page.evaluate(async ({path,method,body})=>{const session=JSON.parse(sessionStorage.getItem('odos.session.v1'));const r=await fetch(path,{method,headers:{Authorization:`Bearer ${session.accessToken}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,body:await r.json()};},{path,method,body});}
async function route(){await page.goto(`${base}/clinic?patientId=${fixture.patientReference.slice(8)}&encounterId=${encounter.id}`);await page.waitForLoadState('networkidle');}
async function ocular(){await page.getByRole('button',{name:'By structure',exact:true}).click();const summary=page.locator('summary').filter({hasText:'Ocular Health'});if(await summary.count()&&!await summary.first().evaluate(el=>el.parentElement.open))await summary.first().click();await page.getByRole('button',{name:/^(Open Lens editor|Edit Lens|Lens.*Expand)$/}).click();await page.getByRole('heading',{name:'Anterior & Posterior Segments'}).waitFor();}
async function shot(name){assert.equal(await page.locator('input[type=password]').count(),0);await page.screenshot({path:join(evidence,name+'.png'),fullPage:true});result.screenshots.push(name+'.png');}
async function save(){await page.getByRole('button',{name:'Save Ocular Health',exact:true}).click();await page.getByRole('button',{name:'Saving…',exact:true}).waitFor({state:'detached'});await page.waitForLoadState('networkidle');}
try{
result.phase='login';await page.goto(base+'/clinic');await page.getByPlaceholder('Email address').fill(credentials.provider.email);await page.getByPlaceholder('Password',{exact:true}).fill(credentials.provider.password);for(let attempt=0;attempt<3;attempt++){const loginReply=page.waitForResponse(r=>r.url().includes('/auth/login'));await page.getByRole('button',{name:'Enter',exact:true}).click();const status=(await loginReply).status();console.log('Login status',status);if(status!==429)break;await page.waitForTimeout(30000);}await page.getByPlaceholder('Password',{exact:true}).waitFor({state:'detached'});result.phase='route';await route();await ocular();
result.phase='absent seed';const seedProjection=await api(`/clinical-graph/encounters/${encounter.id}/findings`);
const offered=seedProjection.body.searchIndex.find(row=>row.key?.optionCode==='nuclear-sclerosis'&&row.eye==='OD');assert.ok(offered);
const absentRequest={commandId:crypto.randomUUID(),patientReference:fixture.patientReference,operation:'assert',targets:[{kind:'fact',key:offered.key,baseline:offered.baseline,state:{status:'live',presence:'absent',qualifiers:{},homes:[]}}]};
const absentResponse=await page.evaluate(async ({path,body})=>{const session=JSON.parse(sessionStorage.getItem('odos.session.v1'));const r=await fetch(path,{method:'PUT',headers:{Authorization:`Bearer ${session.accessToken}`,'Content-Type':'application/json'},body:JSON.stringify(body)});return {status:r.status,body:await r.json()};},{path:`/clinical-graph/encounters/${encounter.id}/findings`,body:absentRequest});assert.equal(absentResponse.status,200);result.absentSeed={request:absentRequest,response:absentResponse};await route();await ocular();
result.phase='absent capture';const lens=page.locator('#structure-ocular-health-anterior-lens');await lens.scrollIntoViewIfNeeded();assert.ok(await lens.getByRole('button',{name:/Nuclear Sclerosis · Recorded absent/i}).count());await shot('recorded-absent');
let projection=await api(`/clinical-graph/encounters/${encounter.id}/findings`);assert.equal(projection.status,200);result.steps.push({name:'Recorded absent',facts:projection.body.searchIndex.filter(row=>row.key?.stableKey==='ocular-health:anterior:lens')});
result.phase='Deferred';const deferred=lens.locator('[data-eye-panel="OS"]').getByRole('button',{name:'Not performed / deferred',exact:true});await deferred.click();await save();await route();await ocular();assert.equal(await deferred.getAttribute('aria-pressed'),'true');await deferred.scrollIntoViewIfNeeded();await shot('deferred');const deferredHistory=await api(`/clinical-graph/custom/ocular-health%3Aanterior%3Alens/history?patient=${fixture.patientReference}&encounter=${encounterReference}`);assert.equal(deferredHistory.status,200);assert.equal(deferredHistory.body.eyes.OS.panel.deferred,true);result.steps.push({name:'Deferred',status:'PASS',panel:deferredHistory.body.eyes.OS.panel});
result.phase='picker';await lens.locator('[data-eye-panel="OD"]').getByRole('button',{name:/^Nuclear Sclerosis/}).click();await save();await lens.scrollIntoViewIfNeeded();const propose=lens.getByRole('button',{name:/^Propose /}).first();await propose.waitFor();const proposalLabel=await propose.getAttribute('aria-label');await propose.click();await lens.getByRole('button',{name:/^Retract proposed /}).first().waitFor();await page.waitForLoadState('networkidle');await lens.getByTestId('structure-diagnosis-rail').scrollIntoViewIfNeeded();await shot('picker-proposal');
projection=await api(`/clinical-graph/encounters/${encounter.id}/findings`);assert.equal(projection.status,200);const supported=projection.body.searchIndex.filter(row=>row.key?.optionCode==='nuclear-sclerosis'&&row.presence==='present');assert.ok(supported.some(row=>row.homes.length));result.steps.push({name:'Picker proposal',proposalLabel,facts:supported,diagnoses:projection.body.visitDiagnoses});
await page.getByRole('button',{name:'By diagnosis',exact:true}).click();await page.locator('.odos-diagnosis-visit-row').first().click();await page.waitForLoadState('networkidle');await page.locator('.odos-diagnosis-provenance').filter({hasText:'nuclear sclerosis'}).waitFor();await shot('diagnosis-origin');writeFileSync(join(evidence,'assessment-visible.txt'),await page.locator('body').innerText());result.steps.push({name:'Diagnosis workspace origin',facts:supported});
result.phase='Assessment section';await page.getByRole('button',{name:'By structure',exact:true}).click();
const assessmentSummary=page.locator('summary').filter({hasText:'Assessment & Plan'});if(await assessmentSummary.count()&&!await assessmentSummary.first().evaluate(el=>el.parentElement.open))await assessmentSummary.first().click();
await page.locator('button[data-editor-section-id="assessment"],button[aria-label="Open Assessment editor"]').first().click();await page.getByRole('heading',{name:'Assessment',exact:true}).first().waitFor();await page.waitForLoadState('networkidle');const assessmentOrigin=page.getByText(/← from nuclear sclerosis/).first();await assessmentOrigin.waitFor({state:'visible'});await assessmentOrigin.scrollIntoViewIfNeeded();assert.ok(await assessmentOrigin.isVisible());await shot('assessment-section-origin');result.steps.push({name:'AssessmentSection origin',status:'PASS',visibleText:await assessmentOrigin.innerText()});
result.phase='confirm carry source';const sourceCard=page.getByTestId('diagnosis-card').filter({hasText:'Age-related nuclear cataract'});await sourceCard.getByRole('button',{name:'Confirm',exact:true}).click();await sourceCard.getByRole('button',{name:'Confirm',exact:true}).waitFor({state:'detached'});await page.waitForLoadState('networkidle');
result.phase='carry fixture';const sourceConditionReference=supported.flatMap(row=>row.homes)[0];assert.ok(sourceConditionReference);
const destination=await operator.fhir.create({...body,status:'in-progress',period:{start:'2026-09-21T14:00:00Z'}});const destinationReference=`Encounter/${destination.id}`;const carryPath=`/clinical-graph/encounters/${destination.id}/previous-exams`;
const firstRequest={commandId:crypto.randomUUID(),sourceEncounterReference:encounterReference,sourceConditionReference};const firstCarry=await api(carryPath,'POST',firstRequest);result.carrySetup={firstRequest,firstCarry,destinationReference};assert.equal(firstCarry.status,200);assert.equal(firstCarry.body.lineageStep,'applied');
const witnesses=await operator.fhir.search('Provenance',{_tag:`urn:odos:carry-command:v1|${firstRequest.commandId}:findings`});assert.equal(witnesses.entry.length,1);const witness=witnesses.entry[0].resource;writeFileSync(join(runtime,`screens-removed-witness-${witness.id}.json`),JSON.stringify(witness,null,2)+'\n',{mode:0o600});
const removed=await fetch(`http://127.0.0.1:${manifest.ports.medplum}/fhir/R4/Provenance/${witness.id}`,{method:'DELETE',headers:{Authorization:`Bearer ${operator.accessToken}`,'If-Match':`W/"${witness.meta.versionId}"`}});assert.ok([200,204].includes(removed.status));const remainingWitnesses=await operator.fhir.search('Provenance',{_tag:`urn:odos:carry-command:v1|${firstRequest.commandId}:findings`});assert.equal(remainingWitnesses.entry?.length??0,0);
const interrupted=await api(carryPath,'POST',{...firstRequest,commandId:crypto.randomUUID()});assert.equal(interrupted.status,409);assert.equal(interrupted.body.reason,'carry-incomplete');
result.interruptedFixture={kind:'Synthetic missing-completion-witness fault injection after successful real carry',sourceEncounter:encounterReference,destination:destinationReference,firstRequest,firstCarry,removedWitness:{reference:`Provenance/${witness.id}`,versionId:witness.meta.versionId},interrupted};
result.phase='carry incomplete UI';await page.goto(`${base}/clinic?patientId=${fixture.patientReference.slice(8)}&encounterId=${destination.id}`);await page.waitForLoadState('networkidle');await page.getByRole('button',{name:'By diagnosis',exact:true}).click();const requests=[];const track=r=>{if(new URL(r.url()).pathname===carryPath)requests.push({method:r.method(),body:r.postData()});};page.on('request',track);
await page.locator(`[data-source-condition-reference="${sourceConditionReference}"]`).click();const recovery=page.getByRole('button',{name:'Reload and carry findings again',exact:true});await recovery.waitFor();await recovery.scrollIntoViewIfNeeded();await shot('carry-incomplete');
const response=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname===carryPath);await recovery.click();const recoveredReply=await response;assert.equal(recoveredReply.status(),200);const recovered=await recoveredReply.json();assert.equal(recovered.lineageStep,'applied');await recovery.waitFor({state:'detached'});page.off('request',track);await page.waitForLoadState('networkidle');await shot('carry-replanned');
const posts=requests.filter(r=>r.method==='POST').map(r=>JSON.parse(r.body));assert.equal(posts.length,2);assert.notEqual(posts[0].commandId,posts[1].commandId);assert.equal(posts[1].replan,true);const lastPostIndex=requests.findLastIndex(r=>r.method==='POST');assert.ok(requests.slice(1,lastPostIndex).some(r=>r.method==='GET'));assert.equal(recovered.conditionReference,firstCarry.body.conditionReference);
result.steps.push({name:'Carry incomplete and replan',status:'PASS',requests,recovered,after:await api(`/clinical-graph/encounters/${destination.id}/findings`)});
result.status=result.steps.some(step=>step.status==='FAIL')?'FAIL':'PASS';result.remaining=[];if(result.status==='FAIL')process.exitCode=1;
}catch(error){result.status='FAIL';result.error=`${error.name}: browser proof failed at ${result.phase}`;if(result.phase!=='login'){result.diagnostic=String(error.message);for(const role of ['admin','provider','staff'])for(const value of Object.values(credentials[role]))if(typeof value==='string')result.diagnostic=result.diagnostic.replaceAll(value,'[redacted]');console.error(result.diagnostic);}if(!await page.locator('input[type=password]').count())await shot('failure');console.error(result.error);process.exitCode=1;}finally{writeFileSync(join(evidence,'result.json'),JSON.stringify(result,null,2)+'\n');await browser.close();}
