import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import type { ClientApplication, ProjectMembership } from '@medplum/fhirtypes';
import { createAuthenticatedFhirClient } from '../../../mcp/tests/integration-helpers.ts';

const base = 'http://localhost:18103/';
const projectId = process.env.MEDPLUM_PROJECT_ID;
assert.ok(projectId);
const admin = await createAuthenticatedFhirClient({ baseUrl: base, email: process.env.MEDPLUM_ADMIN_EMAIL!, password: process.env.MEDPLUM_ADMIN_PASSWORD! });
const headers = { Authorization: `Bearer ${admin.accessToken}`, 'Content-Type': 'application/json' };
const response = await fetch(`${base}admin/projects/${projectId}/client`, { method: 'POST', headers, body: JSON.stringify({ name: 'W1 synthetic runtime service', description: 'Disposable project-scoped MCP proof identity' }) });
assert.equal(response.status, 201, 'runtime client creation');
const client = await response.json() as ClientApplication & { id: string; secret: string };
assert.ok(client.id && client.secret);
const tokenResponse = await fetch(`${base}oauth2/token`, { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ grant_type: 'client_credentials', client_id: client.id, client_secret: client.secret }) });
assert.equal(tokenResponse.status, 200, 'runtime client token');
const token = await tokenResponse.json() as { access_token: string };
const meResponse = await fetch(`${base}auth/me`, { headers: { Authorization: `Bearer ${token.access_token}` } });
assert.equal(meResponse.status, 200, 'runtime client me');
const me = await meResponse.json() as { project?: { id?: string }; membership?: { id?: string } };
assert.equal(me.project?.id, projectId);
assert.ok(me.membership?.id);
const membershipResponse = await fetch(`${base}admin/projects/${projectId}/members/${me.membership.id}`, { headers });
assert.equal(membershipResponse.status, 200, 'runtime membership read');
const membership = await membershipResponse.json() as ProjectMembership;
assert.ok(!membership.accessPolicy && !membership.access?.length, 'runtime has no clinical policy');
const bound = await fetch(`${base}admin/projects/${projectId}/members/${membership.id}`, { method: 'POST', headers, body: JSON.stringify({ ...membership, admin: true }) });
assert.equal(bound.status, 200, 'runtime admin membership bind');
const persisted = await bound.json() as ProjectMembership;
assert.equal(persisted.admin, true);
assert.ok(!persisted.accessPolicy && !persisted.access?.length);
writeFileSync(`${process.env.W1_RUNTIME_DIR}/w1-service.env`, `MEDPLUM_CLIENT_ID=${client.id}\nMEDPLUM_CLIENT_SECRET=${client.secret}\n`, { mode: 0o600 });
console.log('Synthetic project-scoped runtime service ready: project admin, no clinical role policy.');
