import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { test } from 'node:test';
import type { Condition, Observation, Resource } from '@medplum/fhirtypes';
import { buildDiagnosisCatalogSeeds } from '../src/clinical-graph/diagnosis-catalog-seeds.js';
import * as endpoint from '../src/clinical-graph/diagnosis-findings-endpoint.js';
import { buildEncounterDiagnosisCondition } from '../src/fhir/condition.js';
import { SUPPORTS_DIAGNOSIS_URL } from '../src/clinical-graph/current-finding-identity.js';
import { DIAGNOSIS_KEY_IDENTIFIER_SYSTEM } from '../src/clinical-graph/diagnosis-pick-endpoint.js';
import { definitions, atomic, nuclear } from './fixtures/r10/factories.js';
import { canonicalFact, memoryFhir, factTarget, factBaseline, keyFor, endState, httpError } from './fixtures/r10/writer-harness.js';
const encounter = { resourceType: 'Encounter', id: 'e1', status: 'in-progress', class: { code: 'AMB' }, subject: { reference: 'Patient/p1' } } as Resource;
const home = (id = 'x'): Condition => ({ ...buildEncounterDiagnosisCondition({ patientReference: 'Patient/p1', encounterReference: 'Encounter/e1', code: { text: 'Synthetic' }, verificationStatus: 'confirmed', identifiers: [{ system: DIAGNOSIS_KEY_IDENTIFIER_SYSTEM, value: `e1::${nuclear.diagnosisKeys[0]}::right` }] }), id });
const linked = (id = 'canonical', eye: 'OD' | 'OS' = 'OD', homes = ['Condition/x']): Observation => ({ ...canonicalFact(id, eye), extension: [...canonicalFact(id, eye).extension!, ...homes.map(reference => ({ url: SUPPORTS_DIAGNOSIS_URL, valueReference: { reference } }))] });
const setup = (resources: Resource[] = []) => memoryFhir([encounter, ...resources]);
const deps = (m: ReturnType<typeof setup>, actorRole: 'staff' | 'provider' | 'admin' = 'staff'): endpoint.DiagnosisFindingsEndpointDeps => ({ fhirBaseUrl: m.fhir.baseUrl, findingDefinitions: () => definitions, diagnosisCatalog: () => buildDiagnosisCatalogSeeds(), authenticate: async () => ({ staffReference: 'Practitioner/synthetic', actorRole, fhir: { ...m.fhir, create: async (r) => (await m.fhir.createWithOutcome(r)).resource } }) });
const body = (operation: string, targets: unknown[], extra = {}) => ({ commandId: randomUUID(), patientReference: 'Patient/p1', operation, targets, ...extra });
const put = (m: ReturnType<typeof setup>, value: unknown, role: 'staff' | 'provider' | 'admin' = 'staff') => endpoint.handleDiagnosisFindingsMutationRequest(deps(m, role), { authHeader: 'synthetic', params: { encounterId: 'e1' }, body: value });
const get = (m: ReturnType<typeof setup>, condition?: string) => endpoint.handleDiagnosisFindingsReadRequest(deps(m), { authHeader: 'synthetic', params: { encounterId: 'e1' }, query: condition ? { condition } : {} });
const obs = (m: ReturnType<typeof setup>) => m.all<Observation>('Observation');
const baseline = (m: ReturnType<typeof setup>, eye = 'OD') => factBaseline(obs(m), eye, m.all<Condition>('Condition'));
const clinical = (m: ReturnType<typeof setup>) => m.writes.filter(w => w.resource.resourceType !== 'Provenance');
test('W7 staff assert uses chart.write, writes preliminary fact and no Condition', async () => { const m = setup(); const r = await put(m, body('assert', [factTarget()])); assert.equal(r.status, 200); assert.equal((r.body as any).result, 'command'); assert.equal(obs(m)[0].status, 'preliminary'); assert.equal(clinical(m).length, 1); });
test('W27 missing baseline returns 428 and no-store before writes', async () => { const m = setup(); const r = await put(m, body('assert', [{ ...factTarget(), baseline: undefined }])); assert.equal(r.status, 428); assert.equal((r as any).headers['Cache-Control'], 'no-store'); assert.equal(m.writes.length, 0); });
test('W43 pre-rebuild GET is read-only and PUT/repair refuse without writes', async () => { const m = setup([atomic()]); const r = await get(m); assert.equal((r.body as any).encounterEditable, false); assert.equal((r.body as any).readOnlyReason, 'pre-rebuild-test-encounter'); const refused = await put(m, body('assert', [factTarget()])); assert.equal(refused.status, 409); assert.equal((refused.body as any).result, 'invalid'); assert.equal((refused.body as any).reason, 'pre-rebuild-test-encounter'); const repair = (endpoint as any).handleDiagnosisFindingsAuditRepairRequest; assert.equal(typeof repair, 'function'); assert.equal((await repair(deps(m), { params: { encounterId: 'e1' }, body: { commandId: randomUUID(), patientReference: 'Patient/p1' } })).status, 409); assert.equal(m.writes.length, 0); });
test('W39 mixed writable and final target refuses entire command at raw status', async () => { const m = setup([canonicalFact(), { ...canonicalFact('left', 'OS'), status: 'final' }]); const r = await put(m, body('clear', [factTarget(keyFor(), baseline(m), endState({ status: 'retired' })), factTarget(keyFor('OS'), baseline(m, 'OS'), endState({ status: 'retired' }))])); assert.equal(r.status, 422); assert.equal((r.body as any).reason, 'signed-or-cancelled'); assert.equal(m.writes.length, 0); });
test('W26 out-of-domain intended home refuses before any write', async () => { const m = setup(); const r = await put(m, body('assert', [factTarget(keyFor(), undefined, endState({ homes: ['Condition/foreign'] }))], { context: { selectedConditionReference: 'Condition/foreign' } })); assert.equal(r.status, 400); assert.equal(m.writes.length, 0); });
test('W4 assert under Y preserves X in persisted homes and both selected views', async () => { const m = setup([linked(), home(), home('y')]); const r = await put(m, body('assert', [factTarget(keyFor(), baseline(m), endState({ homes: ['Condition/x', 'Condition/y'] }))], { context: { selectedConditionReference: 'Condition/y' } })); assert.equal(r.status, 200); assert.deepEqual(obs(m)[0].extension?.filter(e => e.url === SUPPORTS_DIAGNOSIS_URL).map(e => e.valueReference?.reference), ['Condition/x', 'Condition/y']); for (const ref of ['Condition/x', 'Condition/y']) {
    const selected = await get(m, ref);
    assert.equal(selected.status, 200);
    assert.equal((selected.body as any).findings.filter((r: any) => r.kind === 'fact').length, 1);
    assert.deepEqual((selected.body as any).findings.find((r: any) => r.kind === 'fact').homes, ['Condition/x', 'Condition/y']);
} const invalid = await put(m, body('assert', [factTarget(keyFor(), baseline(m), endState({ homes: ['Condition/y'] }))], { context: { selectedConditionReference: 'Condition/y' } })); assert.equal(invalid.status, 400); });
test('W28a clear preserves historical homes', async () => { const m = setup([linked(), home()]); assert.equal((await put(m, body('clear', [factTarget(keyFor(), baseline(m), endState({ status: 'retired', homes: ['Condition/x'] }))]))).status, 200); assert.equal(obs(m)[0].status, 'entered-in-error'); assert.deepEqual(obs(m)[0].extension?.filter(e => e.url === SUPPORTS_DIAGNOSIS_URL).map(e => e.valueReference?.reference), ['Condition/x']); });
test('W28a clear rejects changed homes without writes', async () => {
    const m = setup([linked(), home(), home('y')]);
    const result = await put(m, body('clear', [factTarget(keyFor(), baseline(m), endState({ status: 'retired', homes: ['Condition/y'] }))]));
    assert.equal(result.status, 400);
    assert.equal((result.body as any).result, 'invalid');
    assert.equal(m.writes.length, 0);
});
for (const operation of ['move', 'standalone', 'link'])
    test(`§3.2 ${operation} rejects changed qualifiers without writes`, async () => {
        const m = setup([linked(), home(), home('y')]);
        const homes = operation === 'standalone' ? [] : operation === 'move' ? ['Condition/y'] : ['Condition/x', 'Condition/y'];
        const result = await put(m, body(operation, [factTarget(keyFor(), baseline(m), endState({ homes, qualifiers: { grade: '2+' } }))], { context: { selectedConditionReference: 'Condition/y' } }));
        assert.equal(result.status, 400);
        assert.equal((result.body as any).result, 'invalid');
        assert.equal(m.writes.length, 0);
    });
test('W28b retired revive links fresh and W33 offered retains revive baseline and same id', async () => { const m = setup([{ ...linked(), status: 'entered-in-error' }, home(), home('y')]); const read = await get(m, 'Condition/y'); const index = (read.body as any).searchIndex; assert.equal((read.body as any).findings.find((r: any) => r.atomicFindingId === nuclear.atomicFindingId && r.eye === 'OD').baseline.reference, 'Observation/canonical'); assert.equal(index.find((r: any) => r.atomicFindingId === nuclear.atomicFindingId && r.eye === 'OD').baseline.kind, 'canonical'); assert.equal((await put(m, body('assert', [factTarget(keyFor(), baseline(m), endState({ homes: ['Condition/y'] }))], { context: { selectedConditionReference: 'Condition/y' } }))).status, 200); assert.equal(obs(m).length, 1); assert.equal(obs(m)[0].id, 'canonical'); assert.deepEqual(obs(m)[0].extension?.filter(e => e.url === SUPPORTS_DIAGNOSIS_URL).map(e => e.valueReference?.reference), ['Condition/y']); });
test('W8 unavailable and W41 410 missing retain typed read failures', async () => { for (const [status, expected, kind] of [[500, 502, 'upstream'], [410, 404, 'missing'], [403, 403, 'refused']] as const) {
    const m = setup();
    m.hooks.beforeSearch = () => { throw httpError(status); };
    const r = await get(m);
    assert.equal(r.status, expected);
    assert.equal((r.body as any).result, 'unavailable');
    assert.equal((r.body as any).kind, kind);
} });
test('W31 conflict carries command result but strips internal fresh', async () => { const m = setup([canonicalFact()]); const r = await put(m, body('assert', [factTarget(keyFor(), { kind: 'canonical', reference: 'Observation/canonical', versionId: 'stale' })])); assert.equal(r.status, 409); assert.equal((r.body as any).outcomes[0].status, 'conflict'); assert.equal(Object.hasOwn((r.body as any).outcomes[0], 'fresh'), false); });
test('W34 same command with fresh baseline and changed state refuses reuse', async () => { const m = setup(); const c = body('assert', [factTarget()]); assert.equal((await put(m, c)).status, 200); assert.equal((await put(m, c)).status, 200); const r = await put(m, { ...c, targets: [factTarget(keyFor(), baseline(m), endState({ presence: 'absent' }))] }); assert.equal(r.status, 409); assert.equal((r.body as any).reason, 'command-reused'); assert.equal(obs(m)[0].valueBoolean, true); assert.equal(clinical(m).length, 1); });
test('W32 eye-change onto differing live destination refuses zero writes', async () => { const m = setup([canonicalFact(), { ...canonicalFact('left', 'OS'), valueBoolean: false }]); const r = await put(m, body('eye-change', [factTarget(keyFor(), baseline(m), endState({ status: 'retired' }))], { eyes: { from: ['OD'], to: ['OS'] } })); assert.equal(r.status, 409); assert.equal((r.body as any).reason, 'destination-differs'); assert.equal(m.writes.length, 0); });
test('OD to OS eye-change creates destination and retires source', async () => { const m = setup([canonicalFact()]); const r = await put(m, body('eye-change', [factTarget(keyFor('OS')), factTarget(keyFor(), baseline(m), endState({ status: 'retired' }))], { eyes: { from: ['OD'], to: ['OS'] } })); assert.equal(r.status, 200); assert.equal(obs(m).length, 2); assert.equal(obs(m).find(o => o.id === 'canonical')?.status, 'entered-in-error'); });
test('W42 repair persists frozen audit debt and clears GET debt without a clinical write', async () => { const m = setup(); m.hooks.beforeWrite = w => { if (w.resource.resourceType === 'Provenance')
    throw httpError(403); }; const r = await put(m, body('assert', [factTarget()])); assert.equal(r.status, 200); assert.equal((r.body as any).complete, false); assert.equal((await get(m)).status, 200); assert.equal(((await get(m)).body as any).auditDebt.length, 1); m.hooks.beforeWrite = undefined; const before = clinical(m).length; const repair = await endpoint.handleDiagnosisFindingsAuditRepairRequest(deps(m), { authHeader: 'synthetic', params: { encounterId: 'e1' }, body: { commandId: randomUUID(), patientReference: 'Patient/p1' } }); assert.equal(repair.status, 200); assert.equal((repair.body as any).complete, true); assert.equal(clinical(m).length, before); assert.equal(m.all('Provenance').length, 1); assert.equal(((await get(m)).body as any).auditDebt.length, 0); });
test('W44 refresh failure selects causal 502 after a confirmed first write', async () => { const m = setup(); m.hooks.afterWrite = w => { if (w.resource.resourceType === 'Provenance')
    m.hooks.beforeSearch = () => { throw httpError(503); }; }; const r = await put(m, body('assert', [factTarget(), factTarget(keyFor('OS'))])); assert.equal(r.status, 502); assert.deepEqual((r.body as any).executionOrder, [0, 1]); assert.equal((r.body as any).outcomes[0].clinicalWrite, 'confirmed'); assert.equal((r.body as any).outcomes[1].cause, 'refresh'); assert.equal((r.body as any).outcomes[1].status, 'not-attempted'); assert.ok(!(r.body as any).outcomes.some((o: any) => Object.hasOwn(o, 'fresh'))); });
for (const operation of ['clear', 'grade', 'move', 'standalone', 'link', 'reassert'])
    test(`retired fact refuses ${operation} without writes`, async () => { const m = setup([{ ...canonicalFact(), status: 'entered-in-error' }, home()]); const target = operation === 'reassert' ? { kind: 'reassert', key: keyFor(), baseline: baseline(m) } : factTarget(keyFor(), baseline(m), endState({ homes: operation === 'move' || operation === 'link' ? ['Condition/x'] : [] })); const r = await put(m, body(operation, [target], { context: { selectedConditionReference: 'Condition/x' } })); assert.equal(r.status, 400); assert.equal(m.writes.length, 0); });
for (const operation of ['move', 'standalone', 'link', 'grade'])
    test(`${operation} changes only authorized state and rejects another state change before writing`, async () => { const m = setup([linked(), home(), home('y')]); const next = endState({ homes: operation === 'standalone' ? [] : operation === 'move' ? ['Condition/y'] : operation === 'link' ? ['Condition/x', 'Condition/y'] : ['Condition/x'], qualifiers: operation === 'grade' ? { grade: '2+' } : {} }); const extra = { context: { selectedConditionReference: 'Condition/y' } }; const bad = await put(m, body(operation, [factTarget(keyFor(), baseline(m), { ...next, presence: 'absent' })], extra)); assert.equal(bad.status, 400); assert.equal(m.writes.length, 0); const good = await put(m, body(operation, [factTarget(keyFor(), baseline(m), next)], extra)); assert.equal(good.status, 200); assert.equal(clinical(m).length, 1); });
for (const status of ['amended', 'corrected', 'cancelled'] as const)
    test(`raw ${status} owner refuses even behind offered row`, async () => { const m = setup([{ ...canonicalFact(), status }]); const rows = ((await get(m)).body as any).searchIndex; const row = rows.find((r: any) => r.atomicFindingId === nuclear.atomicFindingId && r.eye === 'OD'); assert.equal(row.editable, false); assert.equal(row.readOnlyReason, 'signed-or-cancelled'); assert.equal((await put(m, body('assert', [factTarget(keyFor(), baseline(m))]))).status, 422); assert.equal(m.writes.length, 0); });
test('all target structure validated before first write including qualifier, scope, home domain and duplicates', async () => { const examples = [{ ...factTarget(keyFor('OS')), state: endState({ qualifiers: { bad: 2 } }) }, { ...factTarget(keyFor('OS')), key: { ...keyFor('OS'), patientId: 'foreign' } }, { ...factTarget(keyFor('OS')), state: endState({ homes: ['Condition/missing'] }) }, factTarget()]; for (const second of examples) {
    const m = setup();
    const r = await put(m, body('assert', [factTarget(), second]));
    assert.equal(r.status, 400);
    assert.equal(m.writes.length, 0);
    assert.equal((r.body as any).targetIndex, 1);
} });
test('legacy baseline rejected and missing, null and invalid bodies never reach writes', async () => { for (const value of [null, {}, body('assert', [{ ...factTarget(), baseline: { kind: 'legacy', sourceReference: 'Observation/a', versionId: '1', key: keyFor(), mode: 'adopt' } }]), body('assert', [{ ...factTarget(), key: { ...keyFor(), eye: 'OU' } }]), body('assert', [factTarget()], { commandId: '00000000-0000-1000-8000-000000000001' })]) {
    const m = setup();
    assert.equal((await put(m, value)).status, 400);
    assert.equal(m.writes.length, 0);
} });
test('fact with foreign existing home is read-only and cannot be moved away', async () => { const m = setup([linked('canonical', 'OD', ['Condition/foreign']), home()]); const rows = ((await get(m)).body as any).searchIndex; assert.equal(rows.find((r: any) => r.atomicFindingId === nuclear.atomicFindingId && r.eye === 'OD').readOnlyReason, 'home-outside-encounter'); assert.equal((await put(m, body('move', [factTarget(keyFor(), baseline(m), endState({ homes: ['Condition/x'] }))], { context: { selectedConditionReference: 'Condition/x' } }))).status, 400); assert.equal(m.writes.length, 0); });
test('OD to OU writes only added eye and OU to OD retires only removed eye', async () => { const m = setup([canonicalFact()]); assert.equal((await put(m, body('eye-change', [factTarget(keyFor('OS'))], { eyes: { from: ['OD'], to: ['OD', 'OS'] } }))).status, 200); assert.equal(clinical(m).length, 1); assert.equal((await put(m, body('eye-change', [factTarget(keyFor('OS'), baseline(m, 'OS'), endState({ status: 'retired' }))], { eyes: { from: ['OD', 'OS'], to: ['OD'] } }))).status, 200); assert.equal(clinical(m).length, 2); assert.equal(obs(m).find(o => o.id === 'canonical')?.status, 'preliminary'); });
test('eye change revives retired destination and agreeing live destination needs no write', async () => { for (const retired of [true, false]) {
    const m = setup([canonicalFact(), { ...canonicalFact('left', 'OS'), status: retired ? 'entered-in-error' : 'preliminary' }]);
    const targets = [...(retired ? [factTarget(keyFor('OS'), baseline(m, 'OS'))] : []), factTarget(keyFor(), baseline(m), endState({ status: 'retired' }))];
    assert.equal((await put(m, body('eye-change', targets, { eyes: { from: ['OD'], to: ['OS'] } }))).status, 200);
    assert.equal(clinical(m).length, retired ? 2 : 1);
    assert.equal(obs(m).find(o => o.id === 'left')?.status, 'preliminary');
} });
test('OU disagreeing source states cannot collapse and retained eyes cannot be targeted', async () => { for (const differing of [true, false]) {
    const m = setup([canonicalFact(), { ...canonicalFact('left', 'OS'), valueBoolean: !differing }]);
    const r = await put(m, body('eye-change', [factTarget(keyFor(), baseline(m))], { eyes: { from: ['OD', 'OS'], to: ['OD'] } }));
    assert.equal(r.status, 400);
    assert.equal(m.writes.length, 0);
} });
test('command causal response maps every cause by execution order and strips fresh', () => { const outcomes: any[] = [{ status: 'not-attempted', clinicalWrite: 'none', target: 'a', cause: 'halted-by-earlier-target' }, { status: 'conflict', clinicalWrite: 'none', target: 'b', cause: 'verify-read', fresh: { currentFacts: [] } }]; assert.equal(endpoint.findingCommandResponse({ commandId: randomUUID(), complete: false, executionOrder: [1, 0], outcomes }).status, 409); for (const [cause, status, expected] of [['owner-search', 'not-attempted', 502], ['verify-read', 'not-attempted', 502], ['audit-lookup', 'not-attempted', 502], ['audit-repair', 'not-attempted', 503], ['verify-read', 'refused', 422], ['verify-read', 'unconfirmed', 502], ['audit-repair', 'applied', 200]] as const) {
    const r = endpoint.findingCommandResponse({ commandId: randomUUID(), complete: false, executionOrder: [0], outcomes: [{ target: 'a', status, cause, clinicalWrite: 'none' }] });
    assert.equal(r.status, expected);
} for (const cause of ['load', 'refresh'] as const)
    for (const [kind, expected] of [['missing', 404], ['refused', 403], ['upstream', 502], ['foreign-or-unscoped', 502]] as const) {
        const r = endpoint.findingCommandResponse({ commandId: randomUUID(), complete: false, executionOrder: [0], outcomes: [{ target: 'a', status: 'not-attempted', cause, clinicalWrite: 'none', fresh: { incomplete: true, kind, reason: 'synthetic' } }] });
        assert.equal(r.status, expected);
        assert.equal(Object.hasOwn((r.body as any).outcomes[0], 'fresh'), false);
    } });
function carriedSetup() { const prior = { ...home('prior'), encounter: { reference: 'Encounter/prior' } }; const m = setup([linked(), home(), prior, { ...encounter, id: 'prior', period: { start: '2026-09-14T12:00:00.000Z' } } as Resource, { resourceType: 'Provenance', id: 'carry', target: [{ reference: 'Condition/x' }, { reference: 'Observation/canonical' }], recorded: '2026-09-15T12:00:00.000Z', activity: { text: 'Diagnosis pull-forward', coding: [{ system: 'http://terminology.hl7.org/CodeSystem/v3-DataOperation', code: 'CREATE' }] }, agent: [{ who: { reference: 'Practitioner/synthetic' } }], entity: [{ role: 'source', what: { reference: 'Condition/prior' } }] }]); const search = m.fhir.search.bind(m.fhir); m.fhir.search = async (type, params = {}) => { const { target, ...rest } = params; const page = await search(type, rest); if (target)
    page.entry = page.entry?.filter(e => (e.resource as any).target?.some((r: any) => r.reference === target)); return page; }; return m; }
test('W45 reassert fresh-baseline command reuse refuses after version change with exactly one reassert audit', async () => { const m = carriedSetup(); const c = body('reassert', [{ kind: 'reassert', key: keyFor(), baseline: baseline(m) }]); const first = await put(m, c); assert.equal(first.status, 200, JSON.stringify(first.body)); assert.equal(clinical(m).length, 0); assert.equal((await put(m, c)).status, 200); m.save({ ...obs(m)[0], valueBoolean: true }); const replay = await put(m, { ...c, targets: [{ kind: 'reassert', key: keyFor(), baseline: baseline(m) }] }); assert.equal(replay.status, 409); assert.equal((replay.body as any).reason, 'command-reused'); assert.equal(m.all('Provenance').filter((p: any) => p.meta?.tag?.some((t: any) => t.system === 'urn:odos:finding-command:v1')).length, 1); });
test('reassert lookup failure is typed command audit-lookup with no clinical write', async () => { const m = carriedSetup(); m.hooks.beforeSearch = (type, params) => { if (type === 'Provenance' && params._tag?.startsWith('urn:odos:finding-command:v1'))
    throw httpError(503); }; const r = await put(m, body('reassert', [{ kind: 'reassert', key: keyFor(), baseline: baseline(m) }])); assert.equal(r.status, 502); assert.equal((r.body as any).result, 'command'); assert.equal((r.body as any).outcomes[0].cause, 'audit-lookup'); assert.equal((r.body as any).outcomes[0].clinicalWrite, 'none'); assert.equal(m.writes.length, 0); });
test('eye-change identical retry finishes an added eye after removed-first partial application', async () => { const m = setup([linked(), home()]); const c = body('eye-change', [factTarget(keyFor(), baseline(m), endState({ status: 'retired', homes: ['Condition/x'] })), factTarget(keyFor('OS'), undefined, endState({ homes: ['Condition/x'] }))], { eyes: { from: ['OD'], to: ['OS'] } }); m.hooks.beforeWrite = w => { if (w.resource.resourceType === 'Observation' && w.method === 'POST')
    throw httpError(403); }; const first = await put(m, c); assert.equal(first.status, 422); assert.equal((first.body as any).outcomes[0].clinicalWrite, 'confirmed'); m.hooks.beforeWrite = undefined; const retry = await put(m, c); assert.equal(retry.status, 200, JSON.stringify(retry.body)); assert.equal((retry.body as any).complete, true); assert.equal(obs(m).find(o => o.id === 'canonical')?.status, 'entered-in-error'); assert.equal(obs(m).filter(o => o.status === 'preliminary').length, 1); assert.deepEqual(obs(m).find(o => o.status === 'preliminary')?.extension?.filter(e => e.url === SUPPORTS_DIAGNOSIS_URL).map(e => e.valueReference?.reference), ['Condition/x']); });
