import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { test } from 'node:test';
import type { Basic, Encounter, Observation, Provenance, Resource } from '@medplum/fhirtypes';
import { handleEncounterVoidRequest } from '../src/clinical-graph/encounter-void-endpoint.js';
import { handleEncounterUndoRequest } from '../src/clinical-graph/encounter-undo-endpoint.js';
import { FhirEncounterUndoLedgerStore, buildEncounterUndoLedgerResource, parseEncounterUndoLedgerResource } from '../src/clinical-graph/encounter-undo-ledger-store.js';
import { buildFindingDefinitionSeeds, buildFindingDefinitionResource, FhirFindingDefinitionStore } from '../src/clinical-graph/finding-definition-store.js';
import { materializeAtomicFindingCatalog } from '../src/clinical-graph/diagnosis-findings-endpoint.js';
import { findPendingAudits, parseCurrentFindingEnvelope, parseFindingOperation } from '../src/clinical-graph/current-finding-identity.js';
import { type FindingCommandTarget } from '../src/clinical-graph/current-finding-writer.js';
import { AUTH, ENCOUNTER, PATIENT, fixture, observation, seedCanonical, writeFinding, type MemoryFhir } from './encounterVoidFixture.js';

const lens='ocular-health:anterior:lens',cornea='ocular-health:anterior:cornea';
type Fixture=ReturnType<typeof fixture>;
const voidRequest=(f:Fixture,body:unknown)=>handleEncounterVoidRequest(f.deps,{authHeader:AUTH,params:{encounterId:'e1'},body});
const undoRequest=(f:Fixture,voidActionId:unknown,body:Record<string,unknown>={scope:'encounter'})=>handleEncounterUndoRequest(f.deps,{authHeader:AUTH,params:{encounterId:'e1'},body:{...body,...(voidActionId===undefined?{}:{voidActionId})}});
function key(stableKey=lens,eye:'OD'|'OS'='OD',optionIndex=0){const row=materializeAtomicFindingCatalog(buildFindingDefinitionSeeds()).filter(r=>r.findingDefinitionKey===stableKey)[optionIndex];assert.ok(row);return {v:1 as const,patientId:'p1',encounterId:'e1',stableKey,fieldCode:row.fieldCode,optionCode:row.optionCode,eye};}
function target(kind:'fact'|'panel',eye:'OD'|'OS'='OD',baseline?:any):FindingCommandTarget {const k=key(lens,eye);return kind==='fact'?{kind,key:k,baseline:baseline??{kind:'absent',key:k},state:{status:'live',presence:'present',qualifiers:{},homes:[]}}:{kind,key:{v:1,patientId:'p1',encounterId:'e1',stableKey:lens,eye},baseline:baseline??{kind:'absent',key:{v:1,patientId:'p1',encounterId:'e1',stableKey:lens,eye}},state:{deferred:true,values:{},remarks:'preserved'}};}
async function create(f:Fixture,kind:'fact'|'panel'='fact',eye:'OD'|'OS'='OD',debt=false){if(debt)f.fhir.beforeWrite=r=>{if(r.resourceType==='Provenance')throw Error('synthetic audit unavailable');};const result=await writeFinding(f.fhir,target(kind,eye));assert.equal(result.complete,!debt,JSON.stringify(result));f.fhir.beforeWrite=undefined;return f.fhir.get<Observation>('Observation',result.outcomes[0].reference!.split('/')[1]);}
function baseline(o:Observation){return {kind:'canonical' as const,reference:`Observation/${o.id}`,versionId:o.meta!.versionId!};}
function content(o:Observation){const {status:_,meta:__,...rest}=o;return rest;}
const allWrites=(f:Fixture)=>f.fhir.writes.length+f.fhir.transactions.length;
const snapshot=(f:Fixture)=>JSON.stringify(['Observation','Provenance','Basic','Encounter'].map(t=>f.fhir.all(t as Resource['resourceType'])));
async function pending(f:Fixture){return findPendingAudits(f.fhir,f.fhir.all<Observation>('Observation'));}
function ok(r:any){assert.equal(r.status,200,JSON.stringify(r.body));return r.body as any;}

test('W76 canonical section and finding identity include panels and preserve siblings',async()=>{
 for(const scope of ['section','finding'] as const){const f=fixture();const od=await seedCanonical(f.fhir,'od',cornea,'OD'),os=await seedCanonical(f.fhir,'os',cornea,'OS'),sibling=await seedCanonical(f.fhir,'lens',lens,'OD');
 const panelKey={v:1 as const,patientId:'p1',encounterId:'e1',stableKey:cornea,eye:'OD' as const};assert.equal((await writeFinding(f.fhir,{kind:'panel',key:panelKey,baseline:{kind:'absent',key:panelKey},state:{deferred:true,values:{}}})).complete,true);
 const panel=f.fhir.all<Observation>('Observation').find(o=>!['od','os','lens'].includes(o.id!))!;
 const result=ok(await voidRequest(f,scope==='section'?{scope,sectionKey:'ocular-health:anterior:cornea'}:{scope,findingKey:cornea,laterality:'OD'}));
 assert.deepEqual([...result.voided].sort(),[od, ...(scope==='section'?[os]:[]),panel].map(o=>`Observation/${o.id}`).sort(),'canonical identity selects expected owners');
 assert.equal(result.entries.every((e:any)=>e.findingKey===cornea&&e.sectionKey===cornea),true);
 assert.deepEqual(f.fhir.get('Observation','lens'),sibling);if(scope==='finding')assert.deepEqual(f.fhir.get('Observation','os'),os);
 }
});

for(const endpoint of ['void','undo'] as const)for(const kind of ['fact','panel'] as const)test(`W77 ${endpoint} ${kind} repairs real debt before lifecycle and refuses failed repair`,async()=>{
 for(const fail of [false,true]){const f=fixture();let owner=await create(f,kind,'OD',endpoint==='void');let action:any;
 if(endpoint==='undo'){action=ok(await voidRequest(f,{scope:'encounter'})).voidActionId;const audit=f.fhir.all<Provenance>('Provenance').find(p=>p.meta?.tag?.some(t=>t.system==='urn:odos:finding-operation:v1'))!;f.fhir.replace({...audit,meta:{...audit.meta,tag:[]}});}
 assert.equal((await pending(f)).has(`Observation/${owner.id}`),true,'fixture contains actual writer debt');
 const lifecycle=f.fhir.transactions.length,prior=f.fhir.get<Observation>('Observation',owner.id!);
 if(fail)f.fhir.beforeWrite=r=>{if(r.resourceType==='Provenance')throw Error('repair unavailable');};
 f.fhir.beforeTransaction=()=>{assert.equal(f.fhir.all<Provenance>('Provenance').some(p=>p.target.some(t=>t.reference===`Observation/${owner.id}`)&&p.meta?.tag?.some(t=>t.system==='urn:odos:finding-operation:v1')&&p.agent[0].who.reference==='Practitioner/doc1'),true,'audit precedes lifecycle');};
 const result:any=endpoint==='void'?await voidRequest(f,{scope:'encounter'}):await undoRequest(f,action);
 const refused=fail;
 assert.equal(result.status,refused?503:200,JSON.stringify(result.body));assert.equal(f.fhir.transactions.length,lifecycle+(refused?0:1),'repair failure prevents lifecycle');
 if(refused)assert.deepEqual(f.fhir.get('Observation',owner.id!),prior);else assert.equal((await pending(f)).size,0);
 }
});

test('W77 preview never repairs actual debt',async()=>{const f=fixture();await create(f,'fact','OD',true);const before=allWrites(f);ok(await voidRequest(f,{scope:'encounter',preview:true}));assert.equal(allWrites(f),before);assert.equal((await pending(f)).size,1);});

for(const status of ['final','amended','corrected'] as const)for(const kind of ['fact','panel'] as const)test(`W78 ${kind} ${status} signed refusal`,async()=>{const f=fixture(),owner=await create(f,kind,'OD',true);f.fhir.replace({...owner,status});const before=allWrites(f),r:any=await voidRequest(f,{scope:'encounter'});assert.equal(r.status,422);assert.equal(r.body.code,'signed-or-cancelled');assert.equal(allWrites(f),before);});

for(const endpoint of ['void','undo'] as const)test(`W106 ${endpoint} repairs only selected debt`,async()=>{
 const f=fixture();let selected=await create(f,'fact','OD',true);let action:any;
 if(endpoint==='undo'){// Void repairs first, then remove only its audit from the reader's search result.
  action=ok(await voidRequest(f,{scope:'finding',findingKey:lens,laterality:'OD'})).voidActionId;
  const audit=f.fhir.all<Provenance>('Provenance').find(p=>p.meta?.tag?.some(t=>t.system==='urn:odos:finding-operation:v1'))!;
  f.fhir.replace({...audit,meta:{...audit.meta,tag:[]}});
 }
 const unrelated=await create(f,'fact','OS',true);const before=structuredClone(unrelated);
 const r:any=endpoint==='void'?await voidRequest(f,{scope:'finding',findingKey:lens,laterality:'OD'}):await undoRequest(f,action,{scope:'section',sectionKey:lens});ok(r);
 const debt=await pending(f);assert.equal(debt.has(`Observation/${selected.id}`),false);assert.equal(debt.has(`Observation/${unrelated.id}`),true,'outside debt stays pending');assert.deepEqual(f.fhir.get('Observation',unrelated.id!),before);
});

for(const kind of ['fact','panel'] as const)test(`W105 ${kind} writer supersession refuses whole undo`,async()=>{const f=fixture();const original=await create(f,kind),other=await create(f,'fact','OS');const action=ok(await voidRequest(f,{scope:'encounter'})).voidActionId;const retired=f.fhir.get<Observation>('Observation',original.id!);assert.equal((await writeFinding(f.fhir,target(kind,'OD',baseline(retired)))).complete,true);let revived=f.fhir.get<Observation>('Observation',original.id!);if(kind==='fact'){const changed=target('fact','OD',baseline(revived));if(changed.kind==='fact')changed.state.status='retired';assert.equal((await writeFinding(f.fhir,changed)).complete,true);}else {f.fhir.replace({...revived,status:'entered-in-error'});}
 const before=snapshot(f),writes=allWrites(f),r:any=await undoRequest(f,action);assert.equal(r.status,409);assert.equal(r.body.code,'undo-superseded');assert.deepEqual(r.body.superseded,[`Observation/${original.id}`]);assert.equal(allWrites(f),writes);assert.equal(snapshot(f),before);assert.equal(f.fhir.get<Observation>('Observation',other.id!).status,'entered-in-error');});

test('W127 void action UUID is persisted and delayed or consumed undo refuses',async()=>{const f=fixture();await create(f);const v1=ok(await voidRequest(f,{scope:'encounter'}));assert.match(v1.voidActionId,/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i);assert.equal((await new FhirEncounterUndoLedgerStore(f.fhir).get('e1')).encounter?.voidActionId,v1.voidActionId);ok(await undoRequest(f,v1.voidActionId));const v2=ok(await voidRequest(f,{scope:'encounter'}));assert.notEqual(v2.voidActionId,v1.voidActionId);const writes=allWrites(f),before=snapshot(f);const stale:any=await undoRequest(f,v1.voidActionId);assert.equal(stale.status,409);assert.equal(stale.body.code,'undo-superseded');assert.equal(allWrites(f),writes);assert.equal(snapshot(f),before);ok(await undoRequest(f,v2.voidActionId));const consumed:any=await undoRequest(f,v2.voidActionId);assert.equal(consumed.status,409);assert.equal(consumed.body.code,'undo-superseded');});
test('W127 missing void action is 400 zero writes',async()=>{const f=fixture();await create(f);ok(await voidRequest(f,{scope:'encounter'}));const before=allWrites(f);const r:any=await undoRequest(f,undefined);assert.equal(r.status,400);assert.equal(allWrites(f),before);});

for(const endpoint of ['void','undo'] as const)test(`V23 ${endpoint} prebuild refuses before any repair`,async()=>{const f=fixture();await create(f,'fact','OD',true);let action:any;if(endpoint==='undo')action=ok(await voidRequest(f,{scope:'encounter'})).voidActionId;f.fhir.add(observation('legacy',cornea,'OS'));const before=allWrites(f),r:any=endpoint==='void'?await voidRequest(f,{scope:'encounter'}):await undoRequest(f,action);assert.equal(r.status,409);assert.equal(r.body.code,'pre-rebuild-test-encounter');assert.equal(allWrites(f),before);});
for(const endpoint of ['void','undo'] as const)for(const status of ['finished','cancelled','entered-in-error'] as const)test(`V24 ${endpoint} ${status} closed before repair`,async()=>{const f=fixture();const owner=await create(f,'fact','OD',true);let action:any;if(endpoint==='undo')action=ok(await voidRequest(f,{scope:'encounter'})).voidActionId;f.fhir.replace({...f.fhir.get<Encounter>('Encounter','e1'),status});f.fhir.replace({...f.fhir.get<Observation>('Observation',owner.id!),status:'final'});const before=allWrites(f),r:any=endpoint==='void'?await voidRequest(f,{scope:'encounter'}):await undoRequest(f,action);assert.equal(r.status,409);assert.equal(r.body.code,'encounter-closed');assert.equal(allWrites(f),before);});

test('W114 effective stored practice definition resolves lifecycle identity',async()=>{const f=fixture(),defs=buildFindingDefinitionSeeds(),definition=defs.find(d=>d.stableKey===lens)!,fields=structuredClone(definition.valueSchema.fields) as any;const k=key();fields[k.fieldCode].options.push({code:'practice-option',display:'Practice option',active:true});const stored={...definition,sectionKey:'practice-eye',valueSchema:{...definition.valueSchema,fields},sourceStatus:'local-practice' as const};f.fhir.add({...buildFindingDefinitionResource(stored),id:'practice-lens'});const effective=await new FhirFindingDefinitionStore(f.fhir).list();f.deps.findingDefinitions=()=>effective;const customKey={...k,optionCode:'practice-option'};assert.equal((await writeFinding(f.fhir,{kind:'fact',key:customKey,baseline:{kind:'absent',key:customKey},state:{status:'live',presence:'present',qualifiers:{},homes:[]}},effective)).complete,true);const result=ok(await voidRequest(f,{scope:'section',sectionKey:'practice-eye'}));assert.equal(result.count,1);assert.equal(result.entries[0].sectionKey,'practice-eye');ok(await undoRequest(f,result.voidActionId,{scope:'section',sectionKey:'practice-eye'}));});

test('canonical marker null and status-only content round trip',async()=>{const f=fixture(),owner=await seedCanonical(f.fhir,'markerless',lens,'OD');const v=ok(await voidRequest(f,{scope:'encounter'}));assert.equal(v.ledger.encounter.voided[0].markerCommandId,null);ok(await undoRequest(f,v.voidActionId));assert.deepEqual(content(f.fhir.get<Observation>('Observation',owner.id!)),content(owner));assert.equal(f.fhir.get<Observation>('Observation',owner.id!).status,'preliminary');});
test('W105 marker absence transitions refuse without touching unrelated owners',async()=>{for(const transition of ['absent-present','present-absent'] as const){const f=fixture();let owner=transition==='absent-present'?await seedCanonical(f.fhir,'markerless',lens,'OD'):await create(f);const v=ok(await voidRequest(f,{scope:'encounter'}));let current=f.fhir.get<Observation>('Observation',owner.id!);if(transition==='absent-present'){assert.equal((await writeFinding(f.fhir,target('fact','OD',baseline(current)))).complete,true);current=f.fhir.get('Observation',owner.id!);}else current={...current,component:current.component?.filter(c=>!c.code.coding?.some(x=>x.code==='R10_OPERATION'))};f.fhir.replace({...current,status:'entered-in-error'});const before=allWrites(f),r:any=await undoRequest(f,v.voidActionId);assert.equal(r.status,409);assert.equal(r.body.code,'undo-superseded');assert.equal(allWrites(f),before);}});
test('signed canonical outside selection and unrelated final records keep prior behavior',async()=>{const f=fixture(),signed=await create(f);f.fhir.replace({...signed,status:'final'});const unrelated=observation('cvf','entrance:cvf','OD');f.fhir.add(unrelated);const v=ok(await voidRequest(f,{scope:'observation',observationReference:'Observation/cvf'}));ok(await undoRequest(f,v.voidActionId,{scope:'section',sectionKey:'entrance:cvf'}));assert.equal(f.fhir.get<Observation>('Observation','cvf').status,'final');assert.deepEqual(f.fhir.get('Observation',signed.id!),{...signed,status:'final'});});
test('ledger preserves and validates action and marker identities',()=>{const action=randomUUID(),marker=randomUUID(),ledger={encounterId:'e1',encounter:{voidActionId:action,voided:[{ref:'Observation/x',priorStatus:'preliminary',markerCommandId:marker},{ref:'Observation/y',priorStatus:'preliminary',markerCommandId:null}],label:'scope',count:2,at:'synthetic',sectionKeys:[]},sections:{}};assert.deepEqual(parseEncounterUndoLedgerResource(buildEncounterUndoLedgerResource(ledger)),ledger);assert.throws(()=>buildEncounterUndoLedgerResource({...ledger,encounter:{...ledger.encounter,voidActionId:'bad'}}));assert.throws(()=>buildEncounterUndoLedgerResource({...ledger,encounter:{...ledger.encounter,voided:[{ref:'Observation/x',priorStatus:'preliminary',markerCommandId:42}]}} as any));});

for(const status of ['final','amended','corrected'] as const)for(const kind of ['fact','panel'] as const)test(`W78 undo ${kind} ${status} refuses signed canonical owner`,async()=>{const f=fixture(),owner=await create(f,kind);const action=ok(await voidRequest(f,{scope:'encounter'})).voidActionId;f.fhir.replace({...f.fhir.get<Observation>('Observation',owner.id!),status});const before=allWrites(f),r:any=await undoRequest(f,action);assert.equal(r.status,422);assert.equal(r.body.code,'signed-or-cancelled');assert.equal(allWrites(f),before);});
test('preview and empty void return no new action identity',async()=>{const f=fixture();const empty=ok(await voidRequest(f,{scope:'encounter'}));assert.equal(empty.voidActionId,undefined);await create(f,'panel');const before=allWrites(f),preview=ok(await voidRequest(f,{scope:'encounter',preview:true}));assert.equal(preview.voidActionId,undefined);assert.equal(preview.count,1);assert.equal(allWrites(f),before);assert.equal((await new FhirEncounterUndoLedgerStore(f.fhir).get('e1')).encounter,null);});
test('W105 forged audit or malformed operation cannot trigger undo repair before supersession',async()=>{const f=fixture(),owner=await create(f);const action=ok(await voidRequest(f,{scope:'encounter'})).voidActionId;const current=f.fhir.get<Observation>('Observation',owner.id!);f.fhir.replace({...current,component:current.component?.map(c=>c.code.coding?.some(x=>x.code==='R10_OPERATION')?{...c,valueString:'malformed'}:c)});const before=allWrites(f),r:any=await undoRequest(f,action);assert.equal(r.status,409);assert.equal(r.body.code,'undo-superseded');assert.deepEqual(r.body.superseded,[`Observation/${owner.id}`]);assert.equal(allWrites(f),before);});
for(const endpoint of ['void','undo'] as const)test(`V26 ${endpoint} finding lookup outage is structured 503 zero writes`,async()=>{const f=fixture();await create(f);let action:any;if(endpoint==='undo')action=ok(await voidRequest(f,{scope:'encounter'})).voidActionId;const before=allWrites(f),search=f.fhir.search.bind(f.fhir);f.fhir.search=async(type,params)=>{if(type==='Observation')throw Error('synthetic lookup outage');return search(type,params);};const r:any=endpoint==='void'?await voidRequest(f,{scope:'encounter'}):await undoRequest(f,action);assert.equal(r.status,503);assert.equal(r.body.code,'finding-load-failed');assert.equal(allWrites(f),before);});
