import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { test } from 'node:test';
import type { Encounter, Observation, Resource } from '@medplum/fhirtypes';
import { handleCustomSectionCaptureRequest as capture, handleCustomSectionHistoryRequest as history } from '../src/clinical-graph/custom-section-endpoint.js';
import { canonicalFact, memoryFhir, writerContext, command, factTarget, keyFor, factBaseline, endState } from './fixtures/r10/writer-harness.js';
import { lens, lensField, snapshot } from './fixtures/r10/factories.js';
import { executeFindingCommand, repairPendingAudits } from '../src/clinical-graph/current-finding-writer.js';
import { buildSmokingStatusObservation, SMOKING_STATUS_CODES } from '../src/fhir/smokingStatus.js';
import { observationLaterality } from '../src/clinical-graph/current-finding-identity.js';
import { buildFindingDefinitionSeeds, buildFindingDefinitionResource, FhirFindingDefinitionStore } from '../src/clinical-graph/finding-definition-store.js';
import { customFieldEntries } from '../src/clinical-graph/custom-fields.js';
const NOW='2026-09-16T12:00:00.000Z';
const encounter=(id='e1',status:Encounter['status']='in-progress'):Encounter=>({resourceType:'Encounter',id,meta:{versionId:'1'},status,class:{code:'synthetic'},subject:{reference:'Patient/p1'},period:{start:NOW}});
function fixture(initial:Resource[]=[],defs=buildFindingDefinitionSeeds()){
 const m=memoryFhir([encounter(),...initial]);const search=m.fhir.search.bind(m.fhir);
 m.fhir.search=async(type:any,params:any={})=>{
  if(type==='Basic')return {resourceType:'Bundle',type:'searchset',entry:m.all('Basic').filter((r:any)=>!params.code||r.code?.coding?.some((c:any)=>`${c.system}|${c.code}`===params.code)).map(resource=>({resource}))} as any;
  if(type==='Provenance'&&params.target)return {resourceType:'Bundle',type:'searchset',entry:m.all('Provenance').filter((p:any)=>p.target.some((t:any)=>t.reference===params.target)).map(resource=>({resource}))} as any;
  return search(type,params);
 };
 const conditional=m.fhir.createWithOutcome.bind(m.fhir);
 m.fhir.createWithOutcome=async(resource:any,headers:any={})=>{const target=new URLSearchParams(headers['If-None-Exist']??'').get('target');if(target){const found=m.all('Provenance').find((p:any)=>p.target.some((t:any)=>t.reference===target));if(found)return {resource:structuredClone(found),created:false} as any;}return conditional(resource,headers);};
 const fhir={...m.fhir,create:async(resource:any,headers:any)=>(await m.fhir.createWithOutcome(resource,headers)).resource};
 const deps={authenticate:async()=>({staffReference:'Practitioner/synthetic',actorRole:'provider' as const,fhir}),findingDefinitions:()=>defs,now:()=>NOW};return {m,deps};
}
const empty=()=>({loaded:[] as any[],selected:[] as any[]});
const body=(eyes:any)=>({commandId:randomUUID(),patientReference:'Patient/p1',encounterReference:'Encounter/e1',eyes});
const save=(f:ReturnType<typeof fixture>,request:any,key=lens.stableKey)=>capture(f.deps,{authHeader:'synthetic',params:{stableKey:key},body:request});
const read=(f:ReturnType<typeof fixture>,key=lens.stableKey,encounterRef:string|null='Encounter/e1')=>history(f.deps,{authHeader:'synthetic',params:{stableKey:key},query:{patient:'Patient/p1',...(encounterRef?{encounter:encounterRef}:{})}});
const claim=(o?:Observation,key=keyFor()):any=>({key,baseline:o?{kind:'canonical',reference:`Observation/${o.id}`,versionId:o.meta!.versionId}:{kind:'absent',key},presence:'present',qualifiers:{},homes:[]});
const live=(f:ReturnType<typeof fixture>,id='canonical')=>f.m.resources.get(`Observation/${id}`) as Observation;
const panel=(stableKey=lens.stableKey,state:any={deferred:false,values:{}},eye='OD')=>({baseline:{kind:'absent',key:{v:1,patientId:'p1',encounterId:'e1',stableKey,eye}},state});
const negative=(scope=[keyFor().optionCode])=>({id:randomUUID(),scope,exclusions:[] as string[]});
const write=async(f:ReturnType<typeof fixture>,targets:any[])=>executeFindingCommand({...writerContext(f.m),definitions:f.deps.findingDefinitions()},command(targets) as any);
function ok(r:any){assert.equal(r.status,200,JSON.stringify(r.body));assert.equal(r.body.complete,true);}
test('W66 frozen loaded set preserves concurrent addition',async()=>{const f=fixture([canonicalFact()]);const a=claim(live(f));await write(f,[factTarget(keyFor('OD','cortical-cataract'))]);const b=structuredClone(f.m.all<Observation>('Observation').find(o=>o.id!=='canonical'));ok(await save(f,body({OD:{loaded:[a],selected:[]}})));assert.deepEqual(f.m.resources.get(`Observation/${b!.id}`),b);assert.equal(live(f).status,'entered-in-error');});
test('W67 whole request prevalidates stale second eye',async()=>{const f=fixture([canonicalFact('od'),canonicalFact('os','OS')]);const od=claim(live(f,'od')),os=claim(live(f,'os'),keyFor('OS'));os.baseline.versionId='stale';const r:any=await save(f,body({OD:{loaded:[od],selected:[]},OS:{loaded:[],selected:[os]}}));assert.equal(r.status,409);assert.equal(r.body.reason,'stale-baseline');assert.equal(f.m.writes.length,0);});
test('W68 selected positive and scoped negative refuse before writes',async()=>{const f=fixture();const r:any=await save(f,body({OD:{loaded:[],selected:[claim()],negativeAct:negative()}}));assert.equal(r.status,409);assert.equal(r.body.reason,'positive-in-negative-scope');assert.equal(f.m.writes.length,0);});
test('W69 fresh read prevents new negative after concurrent positive',async()=>{const f=fixture();let injected=false;f.m.hooks.afterWrite=(_w,r)=>{if(r.resourceType==='Provenance'&&!injected){injected=true;f.m.save(canonicalFact('concurrent'));}};const r:any=await save(f,body({OD:{...empty(),panel:panel(),negativeAct:negative()}}));assert.equal(r.status,409,JSON.stringify(r.body));assert.equal(r.body.complete,false);assert.equal(r.body.outcomes.at(-1).reason,'positive-in-negative-scope');assert.equal(f.m.all<Observation>('Observation').filter(o=>o.identifier?.some(i=>i.system==='urn:odos:negative-act')).length,0);});
test('W70 deferred preserves fact bytes and version',async()=>{const f=fixture([canonicalFact()]);const before=structuredClone(live(f));ok(await save(f,body({OD:{loaded:[claim(before)],selected:[],panel:panel(lens.stableKey,{deferred:true,values:{}})}})));assert.deepEqual(live(f),before);});
test('W72 current and prior projections hide clears as current',async()=>{const f=fixture([canonicalFact(),encounter('prior')]);ok(await save(f,body({OD:{loaded:[claim(live(f))],selected:[]}})));const k={...keyFor(),encounterId:'prior'},c=command([factTarget(k)]);c.encounterReference='Encounter/prior';await executeFindingCommand(writerContext(f.m),c as any);const r:any=await read(f);assert.equal(r.status,200);assert.equal(r.body.eyes.OD.facts.find((x:any)=>x.key.optionCode===keyFor().optionCode).status,'retired');assert.equal(r.body.eyes.OD.facts.filter((x:any)=>x.status==='live').length,0);const p:any=await read(f,lens.stableKey,null);assert.equal(p.body.encounters.find((x:any)=>x.encounterReference==='Encounter/prior').eyes.OD.facts.filter((x:any)=>x.status==='live').length,1);});
for(const status of ['finished','cancelled','entered-in-error'] as const)test(`W91 ${status} refuses save`,async()=>{const f=fixture();f.m.save(encounter('e1',status));const r:any=await save(f,body({OD:{...empty(),negativeAct:negative()}}));assert.equal(r.status,409);assert.equal(r.body.reason,'encounter-closed');assert.equal(f.m.writes.length,0);});
test('W96 TBUT panel typed values round trip',async()=>{const f=fixture();const d=f.deps.findingDefinitions().find(x=>x.stableKey.endsWith(':tear-film'))!;const fields=customFieldEntries(d),num=fields.find(x=>x.display==='TBUT')!,select=fields.find(x=>x.display==='TBUT method')!;const values={[num.localCode]:5,[select.localCode]:select.options!.find(x=>x.active)!.code};ok(await save(f,body({OD:{...empty(),panel:panel(d.stableKey,{deferred:false,values})}}),d.stableKey));const r:any=await read(f,d.stableKey);assert.deepEqual(r.body.eyes.OD.panel.values,values);assert.equal(f.m.all<Observation>('Observation').some(o=>o.component?.some(c=>c.valueString==='normal')),false);});
test('W97 exact resend completes interrupted eye',async()=>{const f=fixture();let failed=false;f.m.hooks.beforeWrite=w=>{if(w.resource.resourceType==='Observation'&&observationLaterality(w.resource)==='OS'&&!failed){failed=true;throw Error('OS interrupted');}};const req=body({OD:{loaded:[],selected:[claim()]},OS:{loaded:[],selected:[claim(undefined,keyFor('OS'))]}});const first:any=await save(f,req);assert.equal(first.body.complete,false);const od=structuredClone(f.m.all<Observation>('Observation')[0]);f.m.hooks.beforeWrite=undefined;ok(await save(f,req));assert.deepEqual(f.m.resources.get(`Observation/${od.id}`),od);assert.equal(f.m.all('Observation').length,2);});
test('W98 intervening same target stale; unrelated target replay succeeds',async()=>{for(const same of [true,false]){const f=fixture(),req=body({OD:{loaded:[],selected:[claim()]}});ok(await save(f,req));const frozen=JSON.stringify(req);if(same){f.m.save({resourceType:'Condition',id:'c',subject:{reference:'Patient/p1'},encounter:{reference:'Encounter/e1'}} as any);await write(f,[factTarget(keyFor(),factBaseline(f.m.all('Observation')),endState({homes:['Condition/c']}))]);}else await write(f,[factTarget(keyFor('OS'))]);const before=f.m.writes.length,r:any=await save(f,req);assert.equal(r.status,same?409:200,JSON.stringify(r.body));assert.equal(JSON.stringify(req),frozen);if(same){assert.equal(r.body.reason,'stale-baseline');assert.equal(f.m.writes.length,before);}else assert.equal(r.body.outcomes[0].status,'already-applied');}});
test('W99 loaded present claim cannot match live absent',async()=>{const fact={...canonicalFact(),valueBoolean:false},f=fixture([fact]),c=claim(fact),r:any=await save(f,body({OD:{loaded:[c],selected:[c]}}));assert.equal(r.status,409);assert.equal(r.body.reason,'stale-baseline');assert.equal(f.m.writes.length,0);});
test('W100 negative only audit failure is causal incomplete',async()=>{const f=fixture();f.m.hooks.beforeWrite=w=>{if(w.resource.resourceType==='Provenance')throw Error('audit refused');};const r:any=await save(f,body({OD:{...empty(),negativeAct:negative()}}));assert.equal(r.status,503,JSON.stringify(r.body));assert.equal(r.body.complete,false);assert.equal(r.body.outcomes.length,1);assert.equal(r.body.outcomes[0].kind,'negative-act');assert.equal(r.body.outcomes[0].auditPending,true);});
test('W110 panel debt surfaces and repair clears it',async()=>{const f=fixture();f.m.hooks.beforeWrite=w=>{if(w.resource.resourceType==='Provenance')throw Error('audit refused');};const r:any=await save(f,body({OD:{...empty(),panel:panel()}}));assert.equal(r.body.complete,false);const before=structuredClone(f.m.all<Observation>('Observation')[0]),r1:any=await read(f);assert.equal(r1.body.eyes.OD.panel.auditPending,true);f.m.hooks.beforeWrite=undefined;assert.equal((await repairPendingAudits(writerContext(f.m),command([]))).complete,true);const r2:any=await read(f);assert.equal(r2.body.eyes.OD.panel.auditPending??false,false);assert.deepEqual(f.m.resources.get(`Observation/${before.id}`),before);});
test('W114 practice option from stored definitions saves and reads',async()=>{const base=buildFindingDefinitionSeeds().find(d=>d.stableKey===lens.stableKey)!,fields=structuredClone(base.valueSchema.fields) as any;fields[lensField].options.push({code:'practice-option',display:'Practice option',active:true});const stored={...base,sourceStatus:"local-practice" as const,valueSchema:{...base.valueSchema,fields}},f=fixture([{...buildFindingDefinitionResource(stored),id:'stored'}]);const effective=await new FhirFindingDefinitionStore(f.m.fhir as any).list();f.deps.findingDefinitions=()=>effective;ok(await save(f,body({OD:{loaded:[],selected:[claim(undefined,keyFor('OD','practice-option'))]}})));const r:any=await read(f);assert.equal(r.body.eyes.OD.facts.find((x:any)=>x.key.optionCode==='practice-option').status,'live');});
test('W120 persisted negative repairs original audit despite new positive',async()=>{const f=fixture();f.m.hooks.beforeWrite=w=>{if(w.resource.resourceType==='Provenance')throw Error('audit refused');};const req=body({OD:{...empty(),negativeAct:negative()}}),first:any=await save(f,req);assert.equal(first.body.complete,false);f.m.hooks.beforeWrite=undefined;await write(f,[factTarget()]);f.deps.now=()=> '2026-09-17T14:00:00.000Z';ok(await save(f,req));const acts=f.m.all<Observation>('Observation').filter(o=>o.identifier?.some(i=>i.system==='urn:odos:negative-act'));assert.equal(acts.length,1);const audit:any=f.m.all('Provenance').find((p:any)=>p.target.some((t:any)=>t.reference===`Observation/${acts[0].id}`));assert.equal(audit.recorded,NOW);assert.equal(audit.agent[0].who.reference,'Practitioner/synthetic');});
test('W121 same negative id second actor refuses zero writes',async()=>{const f=fixture(),req=body({OD:{...empty(),negativeAct:negative()}});ok(await save(f,req));const auth=f.deps.authenticate;f.deps.authenticate=async()=>({...await auth(),staffReference:'Practitioner/other'});const before=f.m.writes.length,r:any=await save(f,req);assert.equal(r.status,409);assert.equal(r.body.reason,'command-reused');assert.equal(f.m.writes.length,before);});
test('W122 absent transition requires explicit flag; omission preserves',async()=>{const fact={...canonicalFact(),valueBoolean:false},f=fixture([fact]),c=claim(fact),r:any=await save(f,body({OD:{loaded:[],selected:[c]}}));assert.equal(r.status,400);assert.equal(f.m.writes.length,0);ok(await save(f,body({OD:empty()})));assert.deepEqual(live(f),fact);ok(await save(f,body({OD:{loaded:[],selected:[{...c,fromPresence:'absent'}]}})));assert.equal(live(f).valueBoolean,true);});
test('missing baseline 428 no-store and pre-rebuild zero write',async()=>{const f=fixture(),c=claim();delete c.baseline;const r:any=await save(f,body({OD:{loaded:[],selected:[c]}}));assert.equal(r.status,428);assert.equal(r.headers['Cache-Control'],'no-store');const legacy=fixture([snapshot()]),bad:any=await save(legacy,body({OD:empty()}));assert.equal(bad.status,409);assert.equal(bad.body.reason,'pre-rebuild-test-encounter');assert.equal(legacy.m.writes.length,0);});

for(const definition of buildFindingDefinitionSeeds().filter(d=>d.valueSchema.type==='ocular-health-structure'))test(`V18 canonical per-eye fields and qualifiers: ${definition.stableKey}`,async()=>{
 const f=fixture();const make=(eye:'OD'|'OS')=>customFieldEntries(definition).filter(field=>field.valueType==='multi-select').flatMap(field=>(field.options??[]).filter(o=>o.active).map(option=>{
  const key={...keyFor(eye),stableKey:definition.stableKey,fieldCode:field.localCode,optionCode:option.code};
  const qualifiers=Object.fromEntries((option.qualifiers??[]).map(q=>[q.key,q.kind==='graded'?q.options[eye==='OD'?0:q.options.length-1]:q.kind==='enum'?q.options[eye==='OD'?0:q.options.length-1].code:q.kind==='numeric'?(eye==='OD'?q.min:q.max):{from:2,to:5,clockwise:eye==='OD'}]));return {...claim(undefined,key),qualifiers};
 }));
 const od=make('OD'),os=make('OS');ok(await save(f,body({OD:{loaded:[],selected:od},OS:{loaded:[],selected:os}}),definition.stableKey));
 const response:any=await read(f,definition.stableKey);for(const [eye,selected] of [['OD',od],['OS',os]] as const){const facts=response.body.eyes[eye].facts.filter((r:any)=>r.status==='live');assert.equal(facts.length,selected.length);for(const c of selected){const fact=facts.find((r:any)=>r.key.optionCode===c.key.optionCode&&r.key.fieldCode===c.key.fieldCode);assert.ok(fact);assert.deepEqual(fact.qualifiers,c.qualifiers);assert.deepEqual(fact.homes,[]);assert.equal(fact.presence,'present');assert.equal(fact.baseline.kind,'canonical');}}
 assert.equal(f.m.all<Observation>('Observation').every(o=>o.identifier?.some(i=>i.system==='urn:odos:current-finding:v1')),true);
});
for(const scenario of [
 {suffix:'anterior:cornea',codes:['superficial-punctate-keratitis-spk'],details:{'superficial-punctate-keratitis-spk':{grade:'Grade 0'}},expected:['superficial-punctate-keratitis-spk'],expectedDetails:undefined},
 {suffix:'anterior:cornea',codes:['superficial-punctate-keratitis-spk'],details:{'superficial-punctate-keratitis-spk':{grade:'Grade 1'}},expected:['superficial-punctate-keratitis-spk'],expectedDetails:{'superficial-punctate-keratitis-spk':{grade:'Grade 1'}}},
 {suffix:'anterior:lens',codes:['brunescent'],details:{},expected:['nuclear-sclerosis'],expectedDetails:{'nuclear-sclerosis':{colour:'4+ (dark brown/black; brunescent)'}}},
 {suffix:'posterior:macula',codes:['macular-hole-full-lamellar'],details:{},expected:['macular-hole'],expectedDetails:undefined},
 {suffix:'posterior:periphery',codes:['operculated-hole','horseshoe-tear'],details:{},expected:['retinal-hole','retinal-tear'],expectedDetails:{'retinal-hole':{subtype:'operculated'},'retinal-tear':{subtype:'horseshoe'}}},
])test(`V18 W72 legacy ${scenario.suffix} ${scenario.codes.join('+')} remains readable and refuses writes`,async()=>{
 const definition=buildFindingDefinitionSeeds().find(d=>d.stableKey===`ocular-health:${scenario.suffix}`)!;const field=customFieldEntries(definition).find(f=>f.valueType==='multi-select')!;
 const components:any[]=[{code:{coding:[{code:'EXAM_STATE'}]},valueString:'abnormal'},...scenario.codes.map(code=>({code:{coding:[{code:`OD_${field.localCode}::${code}`}]},valueBoolean:true})),...Object.entries(scenario.details).flatMap(([option,details])=>Object.entries(details).map(([q,value])=>({code:{coding:[{code:`OD_${field.localCode}::${option}::${q}`}]},valueCodeableConcept:{coding:[{code:value}]}})))];
 const old={...snapshot('legacy'),code:{coding:[{code:definition.stableKey}]},component:components};const f=fixture([old]);const response:any=await read(f,definition.stableKey);assert.equal(response.body.readOnlyReason,'pre-rebuild-test-encounter');assert.equal(response.body.encounterEditable,false);assert.deepEqual(response.body.rows[0].values.find((v:any)=>v.code===field.localCode).value,scenario.expected);assert.deepEqual(response.body.rows[0].findingDetails,scenario.expectedDetails);const before=structuredClone(live(f,'legacy'));const rejected:any=await save(f,body({OD:empty()}),definition.stableKey);assert.equal(rejected.status,409);assert.equal(f.m.writes.length,0);assert.deepEqual(live(f,'legacy'),before);
});
test('V18 negative scope stays frozen after catalog grows and empty panel never implies a negative',async()=>{
 const f=fixture(),act=negative();ok(await save(f,body({OD:{...empty(),negativeAct:act},OS:{...empty(),panel:panel(lens.stableKey,{deferred:false,values:{}},'OS')}})));
 const defs=structuredClone(f.deps.findingDefinitions());const d=defs.find(d=>d.stableKey===lens.stableKey)!;(d.valueSchema.fields as any)[lensField].options.push({code:'new-option',display:'New option',active:true});f.deps.findingDefinitions=()=>defs;
 const response:any=await read(f);assert.deepEqual(response.body.eyes.OD.negativeActs[0].scope.optionCodes,act.scope);assert.equal(response.body.eyes.OS.negativeActs.length,0);assert.equal(response.body.eyes.OS.panel.deferred,false);assert.equal(f.m.all<Observation>('Observation').some(o=>o.component?.some(c=>c.code.coding?.some(x=>x.code==='EXAM_STATE')&&c.valueString==='normal')),false);
});
test('V18 negative malformed scope and changed payload refuse without replacement',async()=>{
 for(const change of [{scope:[]},{scope:['invented']},{scope:[keyFor().optionCode],exclusions:[keyFor().optionCode]},{actorReference:'Practitioner/forged'}]){const f=fixture(),n={...negative(),...change},r:any=await save(f,body({OD:{...empty(),negativeAct:n}}));assert.equal(r.status,400);assert.equal(f.m.writes.length,0);}
 const f=fixture(),req=body({OD:{...empty(),negativeAct:negative()}});ok(await save(f,req));const before=f.m.writes.length;req.eyes.OD.negativeAct.scope=['cortical-cataract'];const r:any=await save(f,req);assert.equal(r.status,409);assert.equal(r.body.reason,'command-reused');assert.equal(f.m.writes.length,before);
});
test('V18 malformed persisted negative act fails closed on history',async()=>{
 const f=fixture();ok(await save(f,body({OD:{...empty(),negativeAct:negative()}})));const act=f.m.all<Observation>('Observation')[0];for(const text of ['{}','{',JSON.stringify({actorReference:'Practitioner/synthetic',optionCodes:'bad'})]){const changed=structuredClone(act);changed.component!.find(c=>c.code.coding?.some(x=>x.code==='NEGATIVE_ACT'))!.valueString=text;f.m.resources.set(`Observation/${act.id}`,changed);const response:any=await read(f);assert.equal(response.status,503);assert.equal(response.body.reason,'upstream');}
});
test('W96 select-only Surface Staining panel round trips without facts',async()=>{
 const f=fixture(),d=f.deps.findingDefinitions().find(d=>d.valueSchema.type==='ocular-health-structure'&&!customFieldEntries(d).some(x=>x.valueType==='multi-select'))!;assert.ok(d);const values=Object.fromEntries(customFieldEntries(d).filter(x=>x.valueType==='select').map(x=>[x.localCode,x.options!.find(o=>o.active)!.code]));ok(await save(f,body({OD:{...empty(),panel:panel(d.stableKey,{deferred:false,values,remarks:'Measured'})}}),d.stableKey));const r:any=await read(f,d.stableKey);assert.deepEqual(r.body.eyes.OD.panel.values,values);assert.equal(r.body.eyes.OD.facts.length,0);assert.equal(r.body.eyes.OD.panel.remarks,'Measured');
});
test('W97 panel replay uses frozen original baseline',async()=>{const f=fixture(),req=body({OD:{...empty(),panel:panel()}});ok(await save(f,req));const before=structuredClone(f.m.all<Observation>('Observation')[0]);ok(await save(f,req));assert.deepEqual(f.m.resources.get(`Observation/${before.id}`),before);});
test('V18 invalid qualifiers and signed second target refuse the whole request',async()=>{
 const f=fixture(),invalid={...claim(),qualifiers:{grade:'invalid-grade'}};const rejected:any=await save(f,body({OD:{loaded:[],selected:[invalid]}}));assert.equal(rejected.status,400);assert.equal(f.m.writes.length,0);
 const signed={...canonicalFact('signed','OS'),status:'final' as const};const f2=fixture([signed]);const c=claim(signed,keyFor('OS'));const r:any=await save(f2,body({OD:{loaded:[],selected:[claim()]},OS:{loaded:[c],selected:[]}}));assert.equal(r.status,422);assert.equal(f2.m.writes.length,0);
});

test('V18 canonical capture retains ruled lens macula and periphery diagnosis proposals',async()=>{
 const {handleDiagnosisCandidatesRequest}=await import('../src/clinical-graph/diagnosis-candidates-endpoint.js');
 const cases:Array<[string,string,Record<string,string>,string[]]>=[
 ['anterior:lens','nuclear-sclerosis',{grade:'1+'},['cataract_nuclear_sclerosis']],['anterior:lens','nuclear-sclerosis',{grade:'4+'},['cataract_nuclear_sclerosis']],
 ['posterior:periphery','retinal-detachment',{'macula-status':'macula-on'},['retinal_detachment_single_break']],['posterior:periphery','retinal-detachment',{'macula-status':'macula-off'},['retinal_detachment_single_break']],
 ['posterior:macula','epiretinal-membrane-erm',{},['epiretinal_membrane']],['posterior:macula','macular-hole',{},['macular_hole']],['posterior:macula','lamellar-macular-hole',{},['macular_hole']],['posterior:macula','macular-pseudohole',{},['macular_hole']],
 ['posterior:macula','cystoid-macular-edema-cme',{},['cme_following_cataract_surgery','cystoid_macular_degeneration','retinal_edema']],['posterior:macula','geographic-atrophy',{},['nonexudative-amd']],['posterior:macula','cnvm',{},['exudative-amd']],
 ['posterior:periphery','retinal-hole',{subtype:'non-operculated'},['retinal_round_hole']],['posterior:periphery','retinal-hole',{subtype:'operculated'},['retinal_round_hole']],['posterior:periphery','retinal-tear',{subtype:'other'},['retinal_horseshoe_tear']],['posterior:periphery','retinal-tear',{subtype:'horseshoe'},['retinal_horseshoe_tear']],
 ];
 for(const [suffix,option,qualifiers,expected] of cases){const f=fixture(),definition=f.deps.findingDefinitions().find(d=>d.stableKey===`ocular-health:${suffix}`)!,field=customFieldEntries(definition).find(x=>x.valueType==='multi-select')!;const key={...keyFor(),stableKey:definition.stableKey,fieldCode:field.localCode,optionCode:option};ok(await save(f,body({OD:{loaded:[],selected:[{...claim(undefined,key),qualifiers}]}}),definition.stableKey));const response:any=await handleDiagnosisCandidatesRequest({authenticate:f.deps.authenticate},{authHeader:'synthetic',params:{encounterId:'e1'}});assert.equal(response.status,200);const actual=response.body.findings.flatMap((r:any)=>r.candidates.map((c:any)=>c.diagnosisKey??c.familyGroup));assert.deepEqual(actual.sort(),[...expected].sort(),`${suffix}/${option}/${JSON.stringify(qualifiers)}`);assert.equal(f.m.all('Condition').length,0);}
});
test('V18 qualifier omission never fills sibling cells or flare',async()=>{
 const f=fixture(),definition=f.deps.findingDefinitions().find(d=>d.stableKey.endsWith(':anterior-chamber'))!,field=customFieldEntries(definition).find(f=>f.valueType==='multi-select')!;
 const rows=(eye:'OD'|'OS')=>['cells','flare'].map(option=>{const key={...keyFor(eye),stableKey:definition.stableKey,fieldCode:field.localCode,optionCode:option};return {...claim(undefined,key),qualifiers:eye==='OD'&&option==='cells'?{grade:'2+ (16–25)'}:eye==='OS'&&option==='flare'?{grade:'1+ (faint)'}:{}};});
 ok(await save(f,body({OD:{loaded:[],selected:rows('OD')},OS:{loaded:[],selected:rows('OS')}}),definition.stableKey));const r:any=await read(f,definition.stableKey);assert.deepEqual(r.body.eyes.OD.facts.find((x:any)=>x.key.optionCode==='flare').qualifiers,{});assert.deepEqual(r.body.eyes.OS.facts.find((x:any)=>x.key.optionCode==='cells').qualifiers,{});
});
test('V18 panel selects and measurements reject invalid range step owned field and option',async()=>{
 const f=fixture(),definition=f.deps.findingDefinitions().find(d=>d.stableKey.endsWith(':tear-film'))!,fields=customFieldEntries(definition),num=fields.find(x=>x.display==='TBUT')!,select=fields.find(x=>x.display==='TBUT method')!,owned=fields.find(x=>x.valueType==='multi-select')!;
 for(const values of [{[num.localCode]:-1},{[num.localCode]:61},{[num.localCode]:0.5},{[select.localCode]:'invented'},{[owned.localCode]:'invalid'},{unknown:'invalid'}]){const r:any=await save(f,body({OD:{...empty(),panel:panel(definition.stableKey,{deferred:false,values})}}),definition.stableKey);assert.equal(r.status,400);assert.equal(f.m.writes.length,0);}
});

test('V18 all four qualifier kinds stay independent across options and eyes',async()=>{
 const {buildOcularHealthDefinitions}=await import('../src/clinical-graph/ocular-health-definition.js');
 const [definition]=buildOcularHealthDefinitions([{key:'synthetic',display:'Synthetic',normalTemplate:'Synthetic normal',priority:[{key:'a',display:'A',qualifiers:[{kind:'graded',key:'grade',display:'Grade',options:['trace','marked']},{kind:'enum',key:'stability',display:'Stability',options:[{code:'stable',display:'Stable'},{code:'progressive',display:'Progressive'}]},{kind:'numeric',key:'size',display:'Size',min:0,max:10,step:0.5,unit:'mm'},{kind:'extent',key:'span',display:'Span'}]},{key:'b',display:'B',qualifiers:[{kind:'graded',key:'grade',display:'Grade',options:['low','high']}]}],additional:[]}],'ocular-health:synthetic:',{source:'manual',recordedAt:NOW,actorReference:'Practitioner/synthetic'});
 const f=fixture([],[definition]);const field=customFieldEntries(definition)[0];const qualifiers={grade:'trace',stability:'stable',size:2.5,span:{from:2,to:5,clockwise:true}};
 const a={...claim(undefined,{...keyFor(),stableKey:definition.stableKey,fieldCode:field.localCode,optionCode:'a'}),qualifiers};const b={...claim(undefined,{...keyFor(),stableKey:definition.stableKey,fieldCode:field.localCode,optionCode:'b'}),qualifiers:{grade:'high'}};const os={...claim(undefined,{...a.key,eye:'OS'}),qualifiers:{...qualifiers,grade:'marked',size:4}};
 ok(await save(f,body({OD:{loaded:[],selected:[a,b]},OS:{loaded:[],selected:[os]}}),definition.stableKey));const r:any=await read(f,definition.stableKey);assert.deepEqual(r.body.eyes.OD.facts.find((x:any)=>x.key.optionCode==='a').qualifiers,qualifiers);assert.deepEqual(r.body.eyes.OD.facts.find((x:any)=>x.key.optionCode==='b').qualifiers,{grade:'high'});assert.deepEqual(r.body.eyes.OS.facts.find((x:any)=>x.key.optionCode==='a').qualifiers,os.qualifiers);
 const aRecord=f.m.all<Observation>('Observation').find(o=>o.code.coding?.some(c=>c.code?.endsWith('::a'))&&observationLaterality(o)==='OD')!;assert.equal(aRecord.component!.find(c=>c.code.coding?.some(x=>x.code?.endsWith('::size')))?.valueQuantity?.value,2.5);assert.equal((field.options![0].qualifiers!.find(q=>q.key==='size') as any).unit,'mm');
 const invalid={...a,baseline:r.body.eyes.OD.facts.find((x:any)=>x.key.optionCode==='a').baseline,qualifiers:{...qualifiers,size:2.25}};const before=f.m.writes.length;const bad:any=await save(f,body({OD:{loaded:[{...a,baseline:invalid.baseline}],selected:[invalid]}}),definition.stableKey);assert.equal(bad.status,400);assert.equal(f.m.writes.length,before);
});
test('V18 historical aliases are scoped and explicit qualifiers take precedence',async()=>{
 const defs=buildFindingDefinitionSeeds();const definition=defs.find(d=>d.stableKey.endsWith(':periphery'))!,field=customFieldEntries(definition).find(f=>f.valueType==='multi-select')!;
 const old={...snapshot('legacy'),code:{coding:[{code:definition.stableKey}]},component:[{code:{coding:[{code:`OD_${field.localCode}::operculated-hole`}]},valueBoolean:true},{code:{coding:[{code:`OD_${field.localCode}::retinal-hole::subtype`}]},valueCodeableConcept:{coding:[{code:'non-operculated'}]}}]};const f=fixture([old]);const r:any=await read(f,definition.stableKey);assert.equal(r.body.rows[0].findingDetails['retinal-hole'].subtype,'non-operculated');
 const other=structuredClone(defs.find(d=>d.stableKey.endsWith(':cornea'))!);const of=customFieldEntries(other).find(f=>f.valueType==='multi-select')!;(other.valueSchema.fields as any)[of.localCode].options.push({code:'operculated-hole',display:'Synthetic same name',active:true});const foreign={...old,id:'foreign-name',code:{coding:[{code:other.stableKey}]},component:[{code:{coding:[{code:`OD_${of.localCode}::operculated-hole`}]},valueBoolean:true}]};const f2=fixture([foreign],defs.map(d=>d.stableKey===other.stableKey?other:d));const r2:any=await read(f2,other.stableKey);assert.deepEqual(r2.body.rows[0].values.find((v:any)=>v.code===of.localCode).value,['operculated-hole']);assert.equal(r2.body.rows[0].findingDetails,undefined);
});

test('V21 F1 patient-wide priors ignore encounter-less smoking status and retain canonical facts',async()=>{
 const smoking={...buildSmokingStatusObservation({patientReference:'Patient/p1',statusCode:SMOKING_STATUS_CODES[0],effectiveDateTime:NOW}),id:'smoking'};
 const f=fixture([canonicalFact(),smoking]);const result:any=await read(f,lens.stableKey,null);
 assert.equal(result.status,200);assert.equal(result.body.encounters.length,1);
 assert.equal(result.body.encounters[0].eyes.OD.facts.filter((row:any)=>row.status==='live').length,1);
 assert.equal(f.m.writes.length,0);
});
for(const scope of ['foreign','unscoped'] as const)test(`V21 F1 patient-wide contributing ${scope} record is refused`,async()=>{
 const bad=canonicalFact('bad');if(scope==='foreign')bad.subject={reference:'Patient/other'};else delete bad.encounter;
 const f=fixture([canonicalFact()]);const search=f.deps.authenticate;
 f.deps.authenticate=async()=>{const staff=await search();const original=staff.fhir.search.bind(staff.fhir);return {...staff,fhir:{...staff.fhir,search:async(type:any,params:any)=>{
  const result=await original(type,params);if(type==='Observation'&&params.subject&&!params.encounter)result.entry=[...(result.entry??[]),{resource:bad}];return result;
 }}} as any;};
 const result:any=await read(f,lens.stableKey,null);assert.equal(result.status,409);assert.equal(result.body.reason,'foreign-or-unscoped');assert.equal(f.m.writes.length,0);
});
