import { ODOS_OPHTHALMOLOGY_CODE_SYSTEM } from "../src/fhir/ophthalmology/codeBindings.js";
import { handleEncounterVoidRequest } from "../src/clinical-graph/encounter-void-endpoint.js";
import { handleExamOverviewRequest } from "../src/clinical-graph/exam-overview-endpoint.js";
import { buildHpiFindingDefinition } from "../src/clinical-graph/hpi-definition.js";
import { buildEncounterComplaintResource } from "../src/clinical-graph/encounter-complaint-store.js";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import type { Encounter, Observation, Patient, Practitioner } from "@medplum/fhirtypes";
import { createAuthenticatedFhirClient } from "../tests/integration-helpers.js";
import { handleHpiRecordRequest, handleHistoryReviewRequest, handleHpiCaptureRequest, type HpiEndpointDeps } from "../src/clinical-graph/hpi-endpoint.js";
import { buildHistoryAnswerObservation, buildHistoryReviewAttestation, HISTORY_ITEM_REVIEW_CODE, HISTORY_REVIEW_ATTESTATION_CODE_SYSTEM } from "../src/clinical-graph/history-answer-observation.js";
import { searchAll } from "../src/fhir-search.js";

const baseUrl = process.env.MEDPLUM_BASE_URL!;
assert.ok(["localhost", "127.0.0.1"].includes(new URL(baseUrl).hostname));
const { fhir } = await createAuthenticatedFhirClient({ baseUrl, email: process.env.MEDPLUM_ADMIN_EMAIL!, password: process.env.MEDPLUM_ADMIN_PASSWORD! });
const patient = await fhir.create<Patient>({ resourceType: "Patient", active: true, name: [{ text: "Synthetic Item Review" }] });
const patientReference = `Patient/${patient.id}`;
const practitioner = await fhir.create<Practitioner>({ resourceType: "Practitioner", name: [{ text: "Synthetic Item Reviewer" }] });
const staffReference = `Practitioner/${practitioner.id}`;
const encounters = await Promise.all([0, 1].map(() => fhir.create<Encounter>({ resourceType: "Encounter", status: "in-progress", class: { display: "Synthetic test encounter" }, subject: { reference: patientReference } })));
const encounterReference = `Encounter/${encounters[1].id}`;
let now = "2026-09-05T12:00:00Z";
const deps: HpiEndpointDeps = { authenticate: async () => ({ staffReference, actorRole: "provider", fhir }), now: () => now };
const sectionKey = "review-of-systems";
const a = { sectionKey, sectionId: "systems", optionCode: "eye-pain" };
const b = { ...a, optionCode: "poor-vision" };
const c = { ...a, optionCode: "tearing" };
const review = (targets: object[], extra: object = {}) => handleHistoryReviewRequest(deps, { authHeader: "synthetic", body: { patientReference, encounterReference, sectionKey, action: "items-reviewed", method: "bulk", targets, gestureId: randomUUID(), ...extra } });
const retract = (ref: string, gestureId = randomUUID()) => handleHistoryReviewRequest(deps, { authHeader: "synthetic", body: { patientReference, encounterReference, sectionKey, action: "items-review-retracted", targets: [a], retracts: ref, gestureId } });
const read = async () => { const r = await handleHpiRecordRequest(deps, { authHeader: "synthetic", params: { encounterId: encounters[1].id } }); assert.equal(r.status, 200, JSON.stringify(r.body)); return r.body as any; };
const summary = async () => (await read()).subjectSectionSummaries.find((s: any) => s.sectionKey === sectionKey);
const first = await review([a,b,c]); assert.equal(first.status, 200, JSON.stringify(first.body));
const ref = (first.body as any).attestationReference;
const original = await fhir.read<Observation>("Observation", ref.split("/")[1]);
assert.equal((await summary()).state, "charted"); assert.match((await summary()).summary, /Eyes 3\/8/); assert.match((await summary()).summary, /bulk/);
console.log("Bulk act, three of eight Eyes items: HTTP 200; Charted; Eyes 3/8; method bulk");
now = "2026-09-05T13:00:00Z";
const id = randomUUID(), removed = await retract(ref, id); assert.equal(removed.status, 200, JSON.stringify(removed.body));
assert.deepEqual(await fhir.read<Observation>("Observation", original.id!), original);
assert.equal((await read()).lastReviewed.some((r: any) => r.target.optionCode === "eye-pain"), false);
assert.equal((await read()).lastReviewed.find((r: any) => r.target.optionCode === "poor-vision").lastReviewed, "2026-09-05T12:00:00Z");
assert.match((await summary()).summary, /Eyes 2\/8/);
console.log("Retraction A: HTTP 200; A has no date; B retains original date; original resource including version unchanged");
const removedRef = (removed.body as any).attestationReference;
const savedRetraction = await fhir.read<Observation>("Observation", removedRef.split("/")[1]);
assert.deepEqual(await retract(ref, id), removed);
assert.deepEqual(await fhir.read<Observation>("Observation", savedRetraction.id!), savedRetraction);
console.log("Retraction retry: identical response and resource version; no replacement");
const undone = await handleEncounterVoidRequest(deps, { authHeader: "synthetic", params: { encounterId: encounters[1].id }, body: { scope: "observation", observationReference: removedRef } });
assert.equal(undone.status, 200, JSON.stringify(undone.body));
assert.equal((await read()).lastReviewed.find((r: any) => r.target.optionCode === "eye-pain").lastReviewed, "2026-09-05T12:00:00Z");
assert.deepEqual(await fhir.read<Observation>("Observation", original.id!), original);
console.log("Shipped void primitive: HTTP 200; A restored; original byte-identical including version");
await fhir.create(buildEncounterComplaintResource({ id: randomUUID(), patientId: patient.id!, encounterId: encounters[1].id!, ordinal: 1, freeTextLabel: "Synthetic ROS complaint",
  eyeLocation: "OU", conditions: [], qualities: [], treatmentsTried: [], resolvedDx: [], additionalHistory: "", narrative: { mode: "automated" }, status: "active", provenanceHistory: [], provenance: { source: "manual", recordedAt: now, actorReference: staffReference } }));
const save = async (body: object) => { const r = await handleHpiCaptureRequest(deps, { authHeader: "synthetic", body: { patientReference, encounterReference, ...body } }); assert.equal(r.status, 200, JSON.stringify(r.body)); };
await save({ reviewOfSystems: [{ code: "eye-pain", display: "Eye pain", category: "eye", status: "negative" }], reviewAttestations: ["eye"] });
assert.deepEqual((await read()).answers, []);
const aggregate = async () => (await searchAll<Observation>(fhir, "Observation", { encounter: encounterReference, code: `${ODOS_OPHTHALMOLOGY_CODE_SYSTEM}|hpi_ros` }))[0];
const before = await aggregate(); assert.ok(before);
const rosComponents = (o: Observation) => o.component?.filter(c => c.code.coding?.some(v => v.code?.startsWith("ROS_")));
await save({ templateAnswers: [{ id: randomUUID(), subjectScope: "encounter", templateKey: sectionKey, sectionId: "systems", optionCode: "eye-pain", value: { kind: "tri-state", status: "positive" } }] });
assert.deepEqual(rosComponents(await aggregate()), rosComponents(before));
assert.match((await summary()).summary, /Reports eye pain/);
console.log("Legacy/itemized boundary: legacy negative writes zero answers; itemized positive preserves legacy negative and attestation unchanged");
const overview = await handleExamOverviewRequest({ ...deps, findingDefinitions: () => [buildHpiFindingDefinition({ source: "manual", recordedAt: now, actorReference: staffReference })] }, { authHeader: "synthetic", params: { encounterId: encounters[1].id } });
assert.equal(overview.status, 200, JSON.stringify(overview.body)); assert.match((overview.body as any).historySummary, /Eyes 3\/8/); assert.match((overview.body as any).historySummary, /Reports eye pain/);
console.log("Overview chooses Charted itemized coverage and positive while legacy aggregate remains negative");
for (const bad of [{ ...a, extra: true }, { sectionId: "systems", optionCode: "eye-pain" }, ...["sectionKey", "sectionId", "optionCode", "eye"].map(k => ({ ...a, [k]: "*" }))]) assert.equal((await review([bad])).status, 400);
console.log("Malformed JSON targets: six direct endpoint rejections, HTTP 400");
console.log("PASS: 7 local synthetic persistence scenarios; admin client, not a constrained-role AccessPolicy verdict");
