import assert from "node:assert/strict";
import test from "node:test";
import React from "react";
import { act, create } from "react-test-renderer";
import { ResponsiblePartiesControl } from "../src/components/patient/ResponsiblePartiesControl";
test("K14 create-new starts disabled before any keyed search",async()=>{
 const original=globalThis.fetch;
 globalThis.fetch=async(input)=>{const url=new URL(String(input),"http://synthetic.test");const p=url.pathname;const r={resourceType:"RelatedPerson",id:"r",patient:{reference:"Patient/p"},meta:{versionId:"1"},name:[{family:"Ann",given:["Beth"]}]};const person={resourceType:"Person",id:"S",meta:{versionId:"1"},name:r.name,link:[{target:{reference:"RelatedPerson/r"}}]};return Response.json(p.endsWith("/Person")?{resourceType:"Bundle",entry:[{resource:person}]}:p.endsWith("/RelatedPerson")?{resourceType:"Bundle",entry:[{resource:r}]}:p.endsWith("/RelatedPerson/r")?r:p.endsWith("/Person/S")?person:{resourceType:"Patient",id:"p",name:[{given:["Child"]}]});};
 let tree:any;try{await act(async()=>{tree=create(<ResponsiblePartiesControl patientId="p"/>);});const move=tree.root.findAllByType("button").find((x:any)=>x.children.join("")==="Move to another guarantor");assert.ok(move);await act(async()=>move.props.onClick());const button=tree.root.findAllByType("button").find((x:any)=>x.children.join("")==="Create new guarantor");assert.ok(button);assert.equal(button.props.disabled,true);}finally{await act(async()=>tree?.unmount());globalThis.fetch=original;}
});

import { GuarantorLinkScreens } from "../src/components/patient/GuarantorLinkScreens";
const loaded={resourceType:"Person" as const,id:"S",name:[{given:["Loaded"],family:"Ann"}],link:[{target:{reference:"RelatedPerson/r"}}]};
const found={...loaded,id:"D",name:[{given:["Found"],family:"Ann"}]};
const card={personId:"D",versionId:"1",name:"Found Ann",phones:["864-555-0102"],city:"Town",postalCode:"00000"};
async function screen(run:(s:any)=>Promise<void>,options:{conflict?:boolean;cards?:any[];history?:any[]}={}){
 const original=globalThis.fetch;const calls:any[]=[];let reloads=0;let tree:any;
 globalThis.fetch=async(input,init)=>{const url=new URL(String(input),"http://synthetic.test"),body=init?.body?JSON.parse(String(init.body)):undefined;calls.push({path:url.pathname,body});
 if(url.pathname.endsWith("/search"))return Response.json(options.cards??[card]);
 if(url.pathname==="/guarantors")return Response.json({personId:"N",versionId:"1"},{status:201});
 if(url.pathname.endsWith("/draft"))return Response.json({expected:{"Person/S":"1","Person/D":"1","RelatedPerson/r":"1"},relatedPersonIds:body.kind==="consolidate"?["r","r2"]:["r"],patients:[{relatedPersonId:"r",patientId:"p",name:[{given:["Child"]}],current:loaded,resulting:found}]});
 if(url.pathname==="/guarantors/link-operations"&&body)return Response.json(options.conflict?{error:"RelatedPerson/r changed; preview again."}:{task:{id:"op",status:"completed"}},{status:options.conflict?409:200});
 if(url.pathname==="/guarantors/link-operations")return Response.json(options.history??[]);
 if(url.pathname.endsWith("/correct"))return Response.json({task:{status:"completed"}});
 if(url.pathname.endsWith("/Person/D"))return Response.json(found);
 throw Error(`Unexpected request ${url.pathname}`);};
 const buttons=()=>tree.root.findAllByType("button");const button=(text:string)=>buttons().find((b:any)=>b.children.join("")===text);
 const click=async(text:string)=>{const b=button(text);assert.ok(b,`button ${text}`);assert.ok(!b.props.disabled,`enabled ${text}`);await act(async()=>b.props.onClick());};
 const field=async(label:string,value:string)=>{const el=tree.root.findAllByType("label").find((l:any)=>l.children[0]===label);assert.ok(el,label);await act(async()=>el.findByType("input").props.onChange({target:{value}}));};
 const search=async()=>{await field("Search last name","Ann");await field("Search first name","Beth");await click("Search guarantors");};
 try{await act(async()=>{tree=create(<GuarantorLinkScreens person={loaded} relatedPersonId="r" disabled={false} onReload={async()=>{reloads++;}}/>);});await run({calls,tree,button,click,field,search,reloads:()=>reloads});}finally{await act(async()=>tree?.unmount());globalThis.fetch=original;}
}
test("K9 stale confirmation makes one create and requires Review again",async()=>screen(async s=>{await s.click("Move to another guarantor");await s.search();await s.click("Select Found Ann");await s.field("Reason for guarantor change","Correct responsible party");await s.click("Confirm guarantor change");assert.equal(s.calls.filter((c:any)=>c.path==="/guarantors/link-operations"&&c.body).length,1);assert.ok(s.button("Review again"));assert.match(JSON.stringify(s.tree.toJSON()),/changed; preview again/);},{conflict:true}));
test("K10 existing Move drafts before create",async()=>screen(async s=>{await s.click("Move to another guarantor");await s.search();await s.click("Select Found Ann");await s.field("Reason for guarantor change","Move");await s.click("Confirm guarantor change");assert.deepEqual(s.calls.filter((c:any)=>c.body).map((c:any)=>c.path),["/guarantors/link-operations/draft","/guarantors/link-operations"]);assert.equal(s.reloads(),1);}));
test("K10 new Move creates Person before draft and Review again reuses it",async()=>screen(async s=>{await s.click("Move to another guarantor");await s.search();await s.click("Create new guarantor");await s.click("Continue");await s.field("Reason for guarantor change","Move");await s.click("Confirm guarantor change");await s.click("Review again");const writes=s.calls.filter((c:any)=>c.body);assert.deepEqual(writes.map((c:any)=>c.path),["/guarantors","/guarantors/link-operations/draft","/guarantors/link-operations","/guarantors/link-operations/draft"]);assert.equal(writes[1].body.destinationPersonId,"N");assert.equal(writes[2].body.destinationPersonId,"N");assert.equal(writes[3].body.destinationPersonId,"N");},{cards:[],conflict:true}));
for(const keep of ["Loaded Ann","Found Ann"])test(`K11 Join keeps ${keep} and moves loser full set`,async()=>screen(async s=>{await s.click("Join duplicate guarantor records");await s.search();await s.click("Select Found Ann");await s.click(`Keep this record: ${keep}`);await s.field("Reason for guarantor change","Duplicates");await s.click("Confirm guarantor change");const creates=s.calls.filter((c:any)=>c.path==="/guarantors/link-operations"&&c.body);assert.equal(creates.length,1);assert.equal(creates[0].body.destinationPersonId,keep==="Loaded Ann"?"S":"D");assert.equal(creates[0].body.sourcePersonId,keep==="Loaded Ann"?"D":"S");assert.deepEqual(creates[0].body.relatedPersonIds,["r","r2"]);}));
test("K13 Undo only on completed non-correct and requires a reason",async()=>screen(async s=>{await s.click("Guarantor changes");const undo=s.tree.root.findAllByType("button").filter((b:any)=>b.children.join("")==="Undo");assert.equal(undo.length,1);assert.equal(undo[0].props.disabled,true);await s.field("Reason to undo move","Wrong move");await s.click("Undo");assert.equal(s.calls.filter((c:any)=>c.path.endsWith("/correct")).length,1);},{history:[{kind:"transfer",task:{id:"move",status:"completed"},patients:[]},{kind:"correct",task:{id:"correct",status:"completed"},patients:[]},{kind:"consolidate",task:{id:"pending",status:"in-progress"},patients:[]}]}));
test("K14 matching cards require None of these before new guarantor",async()=>screen(async s=>{await s.click("Move to another guarantor");await s.search();assert.equal(s.button("Create new guarantor").props.disabled,true);const box=s.tree.root.findAllByType("input").find((i:any)=>i.props.type==="checkbox");await act(async()=>box.props.onChange({target:{checked:true}}));assert.equal(s.button("Create new guarantor").props.disabled,false);}));

for(const state of ["missing","ambiguous","dangling","unknown","pending"])test(`K12 ${state} offers no Move Join or history Undo`,async()=>{
 const original=globalThis.fetch;let tree:any;const r={resourceType:"RelatedPerson",id:"r",meta:{versionId:"1"},patient:{reference:"Patient/p"},extension:state==="pending"?[{url:"https://odos2020.com/fhir/StructureDefinition/guarantor-link-claim",valueReference:{reference:"Task/op"}}]:[]};
 globalThis.fetch=async(input)=>{const path=new URL(String(input),"http://synthetic.test").pathname;if(path.endsWith("/RelatedPerson"))return Response.json({resourceType:"Bundle",entry:[{resource:r}]});if(path.includes("/guarantors/link-operations/"))return Response.json({active:true,kind:"transfer",task:{id:"op"},sourcePersonId:"S",destinationPersonId:"D",relatedPersonIds:["r"],patients:[]});if(path.endsWith("/Person")){if(state==="unknown")return Response.json({},{status:500});const persons=state==="missing"?[]:state==="ambiguous"?[{...loaded,meta:{versionId:"1"}},{...found,meta:{versionId:"1"}}]:[{...loaded,meta:{versionId:"1"}}];return Response.json({resourceType:"Bundle",entry:persons.map(resource=>({resource}))});}return Response.json({},{status:404});};
 try{await act(async()=>{tree=create(<ResponsiblePartiesControl patientId="p"/>);});const text=JSON.stringify(tree.toJSON());assert.ok(!text.includes('Move to another guarantor'));assert.ok(!text.includes('Join duplicate guarantor records'));assert.ok(!text.includes('Guarantor changes'));assert.ok(!tree.root.findAllByType('button').some((b:any)=>b.children.join('')==='Undo'));}finally{await act(async()=>tree?.unmount());globalThis.fetch=original;}
});

test("K9 uncertain confirmation retry reuses the submitted operation id",async()=>screen(async s=>{await s.click("Move to another guarantor");await s.search();await s.click("Select Found Ann");await s.field("Reason for guarantor change","Move");const base=globalThis.fetch;let dropped=false;globalThis.fetch=async(input,init)=>{const result=await base(input,init);if(String(input)==="/guarantors/link-operations"&&init?.body&&!dropped){dropped=true;throw new Error("Response lost");}return result;};await s.click("Confirm guarantor change");assert.equal(s.reloads(),0);await s.click("Confirm guarantor change");const writes=s.calls.filter((c:any)=>c.path==="/guarantors/link-operations"&&c.body);assert.equal(writes.length,2);assert.deepEqual(writes[1].body,writes[0].body);assert.equal(s.reloads(),1);}));
test("K13 uncertain Undo retry reuses the submitted correction id",async()=>screen(async s=>{await s.click("Guarantor changes");await s.field("Reason to undo move","Wrong move");const base=globalThis.fetch;let dropped=false;globalThis.fetch=async(input,init)=>{const result=await base(input,init);if(String(input).endsWith("/correct")&&!dropped){dropped=true;throw new Error("Response lost");}return result;};await s.click("Undo");assert.equal(s.reloads(),0);await s.click("Undo");const writes=s.calls.filter((c:any)=>c.path.endsWith("/correct"));assert.equal(writes.length,2);assert.deepEqual(writes[1].body,writes[0].body);assert.equal(s.reloads(),1);},{history:[{kind:"transfer",task:{id:"move",status:"completed"},patients:[]}]}));

test("K15 paused create reloads once and closes without Review again or a second create",async()=>screen(async s=>{await s.click("Move to another guarantor");await s.search();await s.click("Select Found Ann");await s.field("Reason for guarantor change","Move");const base=globalThis.fetch;globalThis.fetch=async(input,init)=>{const result=await base(input,init);return String(input)==="/guarantors/link-operations"&&init?.body?Response.json({task:{id:"paused",status:"in-progress"},phase:"attach-pending",active:true,error:"Pending: Complete or Correct."},{status:409}):result;};await s.click("Confirm guarantor change");assert.equal(s.reloads(),1);assert.equal(s.button("Review again"),undefined);assert.equal(s.button("Confirm guarantor change"),undefined);assert.ok(s.button("Move to another guarantor"));assert.equal(s.calls.filter((c:any)=>c.path==="/guarantors/link-operations"&&c.body).length,1);}));
test("K15 paused Undo reloads once and closes without a second correction",async()=>screen(async s=>{await s.click("Guarantor changes");await s.field("Reason to undo move","Wrong move");const base=globalThis.fetch;globalThis.fetch=async(input,init)=>{const result=await base(input,init);return String(input).endsWith("/correct")?Response.json({task:{id:"paused-correct",status:"in-progress"},phase:"attach-pending",active:true,error:"Pending: Complete or Correct."},{status:409}):result;};await s.click("Undo");assert.equal(s.reloads(),1);assert.equal(s.button("Review again"),undefined);assert.equal(s.button("Undo"),undefined);assert.equal(s.calls.filter((c:any)=>c.path.endsWith("/correct")).length,1);},{history:[{kind:"transfer",task:{id:"move",status:"completed"},patients:[]}]}));

for(const action of ["create","Undo"] as const)test(`K15 failed paused ${action} reload locks the screen and reports reload required`,async()=>screen(async s=>{
 if(action==="create"){await s.click("Move to another guarantor");await s.search();await s.click("Select Found Ann");await s.field("Reason for guarantor change","Move");}else{await s.click("Guarantor changes");await s.field("Reason to undo move","Wrong move");}
 let reloads=0;await act(async()=>s.tree.update(<GuarantorLinkScreens person={loaded} relatedPersonId="r" disabled={false} onReload={async()=>{reloads++;throw new Error("Read unavailable");}}/>));
 const base=globalThis.fetch;globalThis.fetch=async(input,init)=>{const result=await base(input,init);return (String(input)==="/guarantors/link-operations"&&init?.body)||String(input).endsWith("/correct")?Response.json({task:{id:"paused",status:"in-progress"},phase:"attach-pending",active:true},{status:409}):result;};
 await s.click(action==="create"?"Confirm guarantor change":"Undo");assert.equal(reloads,1);assert.equal(s.button("Review again"),undefined);assert.equal(s.button(action==="create"?"Confirm guarantor change":"Undo").props.disabled,true);assert.match(JSON.stringify(s.tree.toJSON()),/Reload the patient page before continuing/);const count=s.calls.length;await act(async()=>s.button(action==="create"?"Confirm guarantor change":"Undo").props.onClick());assert.equal(s.calls.length,count);
},{history:[{kind:"transfer",task:{id:"move",status:"completed"},patients:[]}]}));
