import { useRef, useState } from "react";
import type { Person } from "@medplum/fhirtypes";
import { fhir } from "../../lib/fhir";
import { newGuarantorOperationId, searchGuarantors, createNewGuarantor, draftGuarantorOperation, createGuarantorOperation, guarantorOperationHistory, completeGuarantorLinkOperation, correctGuarantorLinkOperation, GuarantorScreenError, type GuarantorSearchCard, type GuarantorDraft, type GuarantorDraftInput, type NewGuarantor, type GuarantorLinkOperation } from "../../lib/guarantor-link-operations";
const empty: NewGuarantor = { firstName:"",middleName:"",lastName:"",phone:"",address:"",city:"",state:"",postalCode:"" };
const name = (p: Pick<Person,"name">) => p.name?.[0]?.text || [...p.name?.[0]?.given ?? [],p.name?.[0]?.family].filter(Boolean).join(" ") || "Unnamed";
function Details({person}:{person:Pick<Person,"name"|"telecom"|"address">}) { return <div><p>{name(person)}</p><p>{person.telecom?.filter(c=>c.system==="phone").map(c=>c.value).join(" · ") || "No phone recorded"}</p><p>{person.address?.map(a=>a.text||[...a.line??[],a.city,a.state,a.postalCode].filter(Boolean).join(", ")).join(" · ")||"No address recorded"}</p></div>; }
function Field({label,value,onChange}:{label:string;value:string;onChange:(s:string)=>void}) {return <label className="grid gap-1">{label}<input className="scheduler-input" value={value} onChange={e=>onChange(e.target.value)}/></label>;}
export function GuarantorLinkScreens({person,relatedPersonId,disabled,onReload}:{person:Person;relatedPersonId:string;disabled:boolean;onReload:()=>Promise<void>}) {
 const [mode,setMode]=useState<"transfer"|"consolidate">();const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");
 const [reloadRequired,setReloadRequired]=useState(false);
 const [last,setLast]=useState("");const [first,setFirst]=useState("");const [phone,setPhone]=useState("");const [keyType,setKeyType]=useState("first");
 const [cards,setCards]=useState<GuarantorSearchCard[]>();const [none,setNone]=useState(false);const [found,setFound]=useState<Person>();
 const [newDetails,setNewDetails]=useState<NewGuarantor>();const [created,setCreated]=useState<string>();const [creationAttempted,setCreationAttempted]=useState(false);
 const [input,setInput]=useState<GuarantorDraftInput>();const [draft,setDraft]=useState<GuarantorDraft>();const [reason,setReason]=useState("");const [review,setReview]=useState(false);
 const [history,setHistory]=useState<GuarantorLinkOperation[]>();const [historyOpen,setHistoryOpen]=useState(false);const [undoReason,setUndoReason]=useState<Record<string,string>>({});
 const attempts=useRef<Record<string,{payload:string;id:string}|undefined>>({});
 const operationIdFor=(key:string,body:object)=>{const payload=JSON.stringify(body);const previous=attempts.current[key];if(previous?.payload===payload)return previous.id;const id=newGuarantorOperationId();attempts.current[key]={payload,id};return id;};
 const reset=()=>{delete attempts.current.confirmation;setMode(undefined);setCards(undefined);setNone(false);setFound(undefined);setNewDetails(undefined);setCreated(undefined);setCreationAttempted(false);setInput(undefined);setDraft(undefined);setReason("");setReview(false);setNotice("");};
 const perform=async(fn:()=>Promise<void>)=>{if(busy||disabled||reloadRequired)return;setBusy(true);setNotice("");try{await fn();}catch(e){if(e instanceof GuarantorScreenError&&e.status===409&&e.body?.task){setReview(false);try{await onReload();reset();setHistory(undefined);setHistoryOpen(false);}catch{setReloadRequired(true);setNotice("The paused operation could not be reloaded. Reload the patient page before continuing.");}return;}setNotice(e instanceof Error?e.message:"Result unknown. Reload before continuing.");if(e instanceof GuarantorScreenError&&e.status===409)setReview(true);}finally{setBusy(false);}};
 const makeDraft=async(next:GuarantorDraftInput)=>{delete attempts.current.confirmation;setInput(next);setDraft(undefined);setReview(false);const value=await draftGuarantorOperation(next);setDraft(value);};
 const transfer=(id:string):GuarantorDraftInput=>({kind:"transfer",sourcePersonId:person.id!,destinationPersonId:id,relatedPersonIds:[relatedPersonId]});
 const changeKeys=(fn:()=>void)=>{fn();setCards(undefined);setNone(false);};
 const select=async(card:GuarantorSearchCard)=>{if(mode==="transfer")await makeDraft(transfer(card.personId));else setFound(await fhir.read<Person>("Person",card.personId));};
 const continueNew=async()=>{if(!newDetails)return;let id=created;if(!id){if(creationAttempted)return;setCreationAttempted(true);const result=await createNewGuarantor(newDetails);id=result.personId;setCreated(id);}await makeDraft(transfer(id));};
 return <div className="grid gap-3 border-t border-[var(--odos-line)] pt-3">
  {!mode&&<div className="flex flex-wrap gap-3"><button type="button" disabled={disabled||busy||reloadRequired} onClick={()=>{reset();setMode("transfer");}}>Move to another guarantor</button><button type="button" disabled={disabled||busy||reloadRequired} onClick={()=>{reset();setMode("consolidate");}}>Join duplicate guarantor records</button></div>}
  {mode&&<fieldset disabled={disabled||busy||reloadRequired} className="grid gap-3"><legend>{mode==="transfer"?"Move this patient":"Join duplicate guarantor records"}</legend>
   {!input&&!newDetails&&!found&&<><Field label="Search last name" value={last} onChange={v=>changeKeys(()=>setLast(v))}/><label>Search with<select value={keyType} onChange={e=>changeKeys(()=>setKeyType(e.target.value))}><option value="first">First name</option><option value="phone">Phone</option></select></label>{keyType==="first"?<Field label="Search first name" value={first} onChange={v=>changeKeys(()=>setFirst(v))}/>:<Field label="Search phone" value={phone} onChange={v=>changeKeys(()=>setPhone(v))}/>}
   <button type="button" disabled={!last.trim()||(keyType==="first"?!first.trim():phone.replace(/\D/g,"").length<10)} onClick={()=>void perform(async()=>{const rows=await searchGuarantors({lastName:last,...keyType==="first"?{firstName:first}:{phone}});setCards(mode==="consolidate"?rows.filter(r=>r.personId!==person.id):rows);setNone(false);})}>Search guarantors</button>
   {cards&&<ul>{cards.map(card=><li key={card.personId} className="rounded border p-3"><p>{card.name}</p><p>{card.phones.join(" · ")}</p><p>{card.city} {card.postalCode}</p><button type="button" onClick={()=>void perform(()=>select(card))}>Select {card.name}</button></li>)}</ul>}
   {cards?.length===0&&<p>No matching guarantors.</p>}{mode==="transfer"&&<>{Boolean(cards?.length)&&<label><input type="checkbox" checked={none} onChange={e=>setNone(e.target.checked)}/>None of these</label>}<button type="button" disabled={cards===undefined||(cards.length>0&&!none)} onClick={()=>setNewDetails({...empty,firstName:first,lastName:last,phone})}>Create new guarantor</button></>}
   </>}
   {newDetails&&<fieldset disabled={creationAttempted}>{Object.entries(newDetails).map(([key,value])=><Field key={key} label={`New guarantor ${{firstName:"first name",middleName:"middle name",lastName:"last name",phone:"phone",address:"address",city:"city",state:"state",postalCode:"postal code"}[key as keyof NewGuarantor]}`} value={value} onChange={v=>setNewDetails({...newDetails,[key]:v})}/>)}<button type="button" disabled={!newDetails.firstName.trim()||!newDetails.lastName.trim()||creationAttempted} onClick={()=>void perform(continueNew)}>Continue</button></fieldset>}
   {found&&!input&&<div className="grid gap-3 sm:grid-cols-2">{[person,found].map(kept=><div key={kept.id} className="rounded border p-3"><Details person={kept}/><button type="button" onClick={()=>void perform(()=>makeDraft({kind:"consolidate",sourcePersonId:kept.id===person.id?found.id!:person.id!,destinationPersonId:kept.id!}))}>Keep this record: {name(kept)}</button></div>)}</div>}
   {draft&&<section aria-label="Confirm guarantor change" className="grid gap-3"><p>{mode==="consolidate"?"The kept record’s details win. The other record is retained, inactive.":person.link?.length===1?"The previous guarantor will be retained, inactive, with no linked patients.":"Only this patient will move."}</p>{draft.patients.map(p=><div key={p.relatedPersonId} className="rounded border p-3"><h4>{name({name:p.name})} — {JSON.stringify(p.current)===JSON.stringify(p.resulting)?"details already match":"details change"}</h4><div className="grid gap-3 sm:grid-cols-2"><div><h5>Current</h5><Details person={p.current}/></div><div><h5>Resulting</h5><Details person={p.resulting}/></div></div></div>)}<Field label="Reason for guarantor change" value={reason} onChange={setReason}/><button type="button" disabled={!reason.trim()||review||reloadRequired} onClick={()=>void perform(async()=>{const body={...input!,relatedPersonIds:draft.relatedPersonIds,expected:draft.expected,reason:reason.trim()};await createGuarantorOperation({...body,operationId:operationIdFor("confirmation",body)});await onReload();reset();setHistory(undefined);setHistoryOpen(false);})}>Confirm guarantor change</button></section>}
   {review&&input&&<button type="button" onClick={()=>void perform(()=>makeDraft(input))}>Review again</button>}
   {created&&<p>The new guarantor record will not be used if you cancel.</p>}<button type="button" onClick={reset}>Cancel</button>
  </fieldset>}
  {notice&&<p role="status">{notice}</p>}
  {!mode&&<><button type="button" disabled={disabled||busy||reloadRequired} aria-expanded={historyOpen} onClick={()=>void perform(async()=>{if(historyOpen){setHistoryOpen(false);return;}setHistory(await guarantorOperationHistory(relatedPersonId));setHistoryOpen(true);})}>Guarantor changes</button>{historyOpen&&<ul>{history?.map(op=><li key={op.task.id} className="grid gap-2 border p-3"><p>{op.kind} · {op.task.meta?.lastUpdated} · {op.patients.map(p=>p.name).join(", ")} · {op.task.status}</p>{op.kind==="correct"&&op.task.status==="in-progress"&&<button type="button" disabled={busy||disabled||reloadRequired} onClick={()=>void perform(async()=>{await completeGuarantorLinkOperation(op.task.id!);await onReload();setHistory(await guarantorOperationHistory(relatedPersonId));})}>Complete</button>}{op.task.status==="completed"&&op.kind!=="correct"&&!op.correctionInProgress&&<><Field label={`Reason to undo ${op.task.id}`} value={undoReason[op.task.id!]??""} onChange={v=>setUndoReason({...undoReason,[op.task.id!]:v})}/><button type="button" disabled={busy||disabled||reloadRequired||!undoReason[op.task.id!]?.trim()} onClick={()=>void perform(async()=>{const reason=undoReason[op.task.id!].trim();await correctGuarantorLinkOperation(op.task.id!,reason,operationIdFor(`undo:${op.task.id}`,{reason}));await onReload();setHistory(await guarantorOperationHistory(relatedPersonId));setUndoReason({});})}>Undo</button></>}</li>)}</ul>}</>}
 </div>;
}
