import {readFileSync} from 'node:fs';
import {loadVerifiedOperatorFhirClient} from '../../../../scripts/operator-identity.js';
import {buildVisitType,ODOS_VISIT_TYPE_SYSTEM} from '../../../../mcp/src/fhir/schedulingVisitType.js';
import {buildSchedulingAppointment} from '../../../../mcp/src/fhir/schedulingAppointment.js';
import {disciplineCoding} from '../../../../mcp/src/scheduling/clinic-mode.js';
const runtime='.odos/s1-proof';
const read=(n:string)=>JSON.parse(readFileSync(`${runtime}/${n}`,'utf8'));
const {ports}=read('manifest.json'),credentials=read('credentials.json'),fixture=read('fixture.json');
const {database}=read('medplum.config.json');
const {fhir}=await loadVerifiedOperatorFhirClient({baseUrl:`http://127.0.0.1:${ports.medplum}`,projectId:credentials.projectId,postgresUrl:`postgresql://${database.username}:${database.password}@127.0.0.1:${ports.postgres}/${database.dbname}`,credentialPath:`${runtime}/operator.env`,statePath:`${runtime}/operator-state.json`});
const code='s1-comprehensive';
await fhir.create(buildVisitType({code,name:'S1 Synthetic Comprehensive',discipline:'eyecare',durationMinutes:30,categoryCode:'comprehensive',categoryLabel:'Comprehensive'}));
const appointment=await fhir.create(buildSchedulingAppointment({patient:{reference:fixture.patientReference},visitTypeCode:code,visitTypeDisplay:'S1 Synthetic Comprehensive',discipline:'eyecare',resources:[{reference:credentials.provider.practitionerReference}],start:'2026-09-19T14:00:00Z',durationMinutes:30}));
const encounter=await fhir.read<any>('Encounter',fixture.current.slice(10));
await fhir.update('Encounter',encounter.id,{...encounter,type:[{coding:[{system:ODOS_VISIT_TYPE_SYSTEM,code,display:'S1 Synthetic Comprehensive'}]}],serviceType:{coding:[disciplineCoding('eyecare')]},appointment:[{reference:`Appointment/${appointment.id}`}]},{'If-Match':`W/"${encounter.meta.versionId}"`});
console.log('Synthetic encounter now uses the comprehensive visit category.');
