import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {buildFindingDefinitionSeeds} from '../../../mcp/src/clinical-graph/finding-definition-store.ts';
import {materializeAtomicFindingCatalog,handleDiagnosisFindingsMutationRequest} from '../../../mcp/src/clinical-graph/diagnosis-findings-endpoint.ts';
import {customFieldEntries} from '../../../mcp/src/clinical-graph/custom-fields.ts';
import {classifyFindingObservation,FINDING_PANEL_SYSTEM,matchesFindingAudit,FINDING_OPERATION_AUDIT_SYSTEM} from '../../../mcp/src/clinical-graph/current-finding-identity.ts';
import {projectCurrentFindings} from '../../../mcp/src/clinical-graph/current-finding-reader.ts';
import {executeFindingCommand,classifyReplay} from '../../../mcp/src/clinical-graph/current-finding-writer.ts';
import {snapshot,comp,lens,definitions,state} from '../../../mcp/tests/fixtures/r10/factories.ts';
import {canonicalFact,keyFor,memoryFhir,writerContext,command,factTarget,factBaseline,httpError} from '../../../mcp/tests/fixtures/r10/writer-harness.ts';
const log=(id:string,detail:any)=>console.log(JSON.stringify({id,status:'VERIFIED',detail}));
const all=buildFindingDefinitionSeeds(), catalog=materializeAtomicFindingCatalog(all);
const shared=all.filter(d=>d.valueSchema.type==='ocular-health-structure');
const nonshared=catalog.filter(r=>!shared.some(d=>d.stableKey===r.findingDefinitionKey));
assert.equal(all.length,47);assert.equal(shared.length,15);assert.equal(shared.filter(d=>customFieldEntries(d).some(f=>f.valueType==='multi-select')).length,14);assert.equal(catalog.length,405);assert.equal(nonshared.length,177);assert.equal(new Set(nonshared.map(r=>r.findingDefinitionKey)).size,15);
assert.equal(classifyFindingObservation(snapshot(),all,catalog,new Map()).kind,'legacy-section-snapshot');
assert.equal(projectCurrentFindings({...state([snapshot()]),definitions:all,catalog}).preRebuild,true);
log('P1',{definitions:47,shared:15,sharedMulti:14,catalog:405,nonshared:177,nonsharedDefinitions:15,snapshotPreRebuild:true});
const panel={...snapshot(),identifier:[{system:FINDING_PANEL_SYSTEM,value:'unverified-id'}],component:[comp('EXAM_STATE','deferred'),comp('OTHER','other'),comp('REMARKS','remarks')]};
const pp=projectCurrentFindings(state([panel]));
assert.equal(classifyFindingObservation(panel,definitions,materializeAtomicFindingCatalog(definitions),new Map()).kind,'panel-context');
assert.equal(pp.panels[0].deferred,true);assert.equal(pp.panels[0].other,'other');assert.equal(pp.panels[0].remarks,'remarks');
log('P2',{identifierOnly:true,hydrated:pp.panels[0]});
const tear=shared.find(d=>d.stableKey.endsWith(':tear-film'))!;
const surface=shared.find(d=>d.stableKey==='dry-eye:conjunctival-staining')!;
assert.ok(customFieldEntries(tear).some(f=>f.valueType==='number'&&f.display==='TBUT'));
assert.ok(customFieldEntries(tear).some(f=>f.valueType==='select'&&f.display==='TBUT method'));
assert.ok(customFieldEntries(surface).every(f=>f.valueType==='select'));
log('P4',{tear:customFieldEntries(tear),surface:customFieldEntries(surface)});
const closed=memoryFhir([{resourceType:'Encounter',id:'e1',status:'finished',class:{code:'synthetic'},subject:{reference:'Patient/p1'}} as any]);
const result=await handleDiagnosisFindingsMutationRequest({fhirBaseUrl:closed.fhir.baseUrl,authenticate:async()=>({staffReference:'Practitioner/synthetic',actorRole:'provider',fhir:closed.fhir as any}),findingDefinitions:()=>definitions},
{authHeader:'synthetic',params:{encounterId:'e1'},body:{commandId:randomUUID(),patientReference:'Patient/p1',operation:'assert',targets:[factTarget()]}});
assert.equal(result.status,200,JSON.stringify(result));assert.equal(closed.all('Observation').length,1);
log('P6',{status:result.status,observationWrites:closed.all('Observation').length});
const inactive=definitions.map(d=>d.stableKey===lens.stableKey?{...d,active:false}:d);
const inactiveProjection=projectCurrentFindings({...state([canonicalFact()]),definitions:inactive,catalog:materializeAtomicFindingCatalog(inactive)});
assert.equal(inactiveProjection.preRebuild,true);assert.equal(inactiveProjection.currentFacts.length,0);
log('P7',{preRebuild:true,unresolved:inactiveProjection.unresolved});
const forged={resourceType:'Provenance',target:[{reference:'Observation/any'}],recorded:'2020-01-01T00:00:00Z',agent:[{who:{reference:'Practitioner/forged'}}],meta:{tag:[{system:FINDING_OPERATION_AUDIT_SYSTEM,code:'key'}]}} as any;
assert.equal(matchesFindingAudit(forged,'key','Observation/any'),true);
log('P17',{forgedActorAccepted:true});
for(const status of [404,410]) {
 const m=memoryFhir([canonicalFact()]);const baseline=factBaseline(m.all('Observation') as any);
 m.hooks.beforeRead=type=>{if(type==='Observation')throw httpError(status);};
 const r=await executeFindingCommand(writerContext(m),command([{kind:'reassert',key:keyFor(),baseline}]) as any);
 assert.equal(r.outcomes[0].status,status===404?'conflict':'not-attempted');
 log('P18',{httpStatus:status,outcome:r.outcomes[0].status});
}
const m=memoryFhir([canonicalFact()]);const c=command([{kind:'reassert',key:keyFor(),baseline:factBaseline(m.all('Observation') as any)}]);
assert.equal((await executeFindingCommand(writerContext(m),c as any)).complete,true);
m.resources.delete('Observation/canonical');
const replay=await executeFindingCommand(writerContext(m),c as any);
assert.equal(replay.outcomes[0].status,'already-applied');
const m2=memoryFhir();const c2=command([factTarget()]);await executeFindingCommand(writerContext(m2),c2 as any);
const record=m2.all('Observation')[0] as any;m2.save({...record,status:'entered-in-error'});
const replayClass=await classifyReplay({...state(m2.all('Observation') as any),fhir:m2.fhir} as any,c2 as any,c2.targets[0] as any);
assert.equal(replayClass,'not-replay');
log('P26',{deletedReassert:replay.outcomes[0].status,changedFact:replayClass});
